// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
internal class LocalizableSymbol: SFSymbol, ar, he, hi, rtl, ja, ko, th, zh, zhTraditional, ar_v2, he_v2, hi_v2, rtl_v2, ja_v2, ko_v2, th_v2, zh_v2, zhTraditional_v2, ar_v2_1, he_v2_1, hi_v2_1, rtl_v2_1, ja_v2_1, ko_v2_1, th_v2_1, zh_v2_1, zhTraditional_v2_1, ar_v2_2, he_v2_2, hi_v2_2, rtl_v2_2, ja_v2_2, ko_v2_2, th_v2_2, zh_v2_2, zhTraditional_v2_2, ar_v3, he_v3, hi_v3, rtl_v3, ja_v3, ko_v3, th_v3, zh_v3, zhTraditional_v3, ar_v3_1, he_v3_1, hi_v3_1, rtl_v3_1, ja_v3_1, ko_v3_1, th_v3_1, zh_v3_1, zhTraditional_v3_1 {
    var ar: SFSymbol { .init(rawValue: "\(rawValue).ar") }
    var he: SFSymbol { .init(rawValue: "\(rawValue).he") }
    var hi: SFSymbol { .init(rawValue: "\(rawValue).hi") }
    var rtl: SFSymbol { .init(rawValue: "\(rawValue).rtl") }
    var ja: SFSymbol { .init(rawValue: "\(rawValue).ja") }
    var ko: SFSymbol { .init(rawValue: "\(rawValue).ko") }
    var th: SFSymbol { .init(rawValue: "\(rawValue).th") }
    var zh: SFSymbol { .init(rawValue: "\(rawValue).zh") }
    var zhTraditional: SFSymbol { .init(rawValue: "\(rawValue).zh.traditional") }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ar {
    var ar: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol he {
    var he: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol hi {
    var hi: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol rtl {
    var rtl: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ja {
    var ja: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ko {
    var ko: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol th {
    var th: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zh {
    var zh: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zhTraditional {
    var zhTraditional: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ar_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var ar: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol he_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var he: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol hi_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var hi: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol rtl_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var rtl: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ja_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var ja: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ko_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var ko: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol th_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var th: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zh_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var zh: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zhTraditional_v2 {
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *)
    var zhTraditional: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ar_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var ar: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol he_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var he: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol hi_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var hi: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol rtl_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var rtl: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ja_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var ja: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ko_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var ko: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol th_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var th: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zh_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var zh: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zhTraditional_v2_1 {
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
    var zhTraditional: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ar_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var ar: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol he_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var he: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol hi_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var hi: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol rtl_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var rtl: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ja_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var ja: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ko_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var ko: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol th_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var th: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zh_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var zh: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zhTraditional_v2_2 {
    @available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
    var zhTraditional: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ar_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var ar: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol he_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var he: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol hi_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var hi: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol rtl_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var rtl: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ja_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var ja: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ko_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var ko: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol th_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var th: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zh_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var zh: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zhTraditional_v3 {
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *)
    var zhTraditional: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ar_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var ar: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol he_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var he: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol hi_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var hi: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol rtl_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var rtl: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ja_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var ja: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol ko_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var ko: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol th_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var th: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zh_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var zh: SFSymbol { get }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public protocol zhTraditional_v3_1 {
    @available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
    var zhTraditional: SFSymbol { get }
}