// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 7.0 Symbols
@available(iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0, visionOS 26.0, *)
public extension SFSymbol {
    /// 􃌦
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _1Calendar = SFSymbol(rawValue: "1.calendar")

    /// 􃌯
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _10Calendar = SFSymbol(rawValue: "10.calendar")

    /// 􃌰
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _11Calendar = SFSymbol(rawValue: "11.calendar")

    /// 􃌱
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _12Calendar = SFSymbol(rawValue: "12.calendar")

    /// 􃌲
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _13Calendar = SFSymbol(rawValue: "13.calendar")

    /// 􃌳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _14Calendar = SFSymbol(rawValue: "14.calendar")

    /// 􃌴
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _15Calendar = SFSymbol(rawValue: "15.calendar")

    /// 􃌵
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _16Calendar = SFSymbol(rawValue: "16.calendar")

    /// 􃌶
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _17Calendar = SFSymbol(rawValue: "17.calendar")

    /// 􃌷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _18Calendar = SFSymbol(rawValue: "18.calendar")

    /// 􃌸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _19Calendar = SFSymbol(rawValue: "19.calendar")

    /// 􃌧
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _2Calendar = SFSymbol(rawValue: "2.calendar")

    /// 􃌹
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _20Calendar = SFSymbol(rawValue: "20.calendar")

    /// 􃌺
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _21Calendar = SFSymbol(rawValue: "21.calendar")

    /// 􃌻
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _22Calendar = SFSymbol(rawValue: "22.calendar")

    /// 􃌼
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _23Calendar = SFSymbol(rawValue: "23.calendar")

    /// 􃌽
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _24Calendar = SFSymbol(rawValue: "24.calendar")

    /// 􃌾
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _25Calendar = SFSymbol(rawValue: "25.calendar")

    /// 􃌿
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _26Calendar = SFSymbol(rawValue: "26.calendar")

    /// 􃍀
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _27Calendar = SFSymbol(rawValue: "27.calendar")

    /// 􃍁
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _28Calendar = SFSymbol(rawValue: "28.calendar")

    /// 􃍂
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _29Calendar = SFSymbol(rawValue: "29.calendar")

    /// 􃌨
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _3Calendar = SFSymbol(rawValue: "3.calendar")

    /// 􃍃
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _30Calendar = SFSymbol(rawValue: "30.calendar")

    /// 􃍄
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _31Calendar = SFSymbol(rawValue: "31.calendar")

    /// 􃌩
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _4Calendar = SFSymbol(rawValue: "4.calendar")

    /// 􃌪
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _5Calendar = SFSymbol(rawValue: "5.calendar")

    /// 􃌫
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _6Calendar = SFSymbol(rawValue: "6.calendar")

    /// 􃌬
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _7Calendar = SFSymbol(rawValue: "7.calendar")

    /// 􃌭
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _8Calendar = SFSymbol(rawValue: "8.calendar")

    /// 􃌮
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let _9Calendar = SFSymbol(rawValue: "9.calendar")

    /// 􃈜
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let airplaneCloud = SFSymbol(rawValue: "airplane.cloud")

    /// 􃈛
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let airplaneLanded = SFSymbol(rawValue: "airplane.landed")

    /// 􃋁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let airplanePathDotted = SFSymbol(rawValue: "airplane.path.dotted")

    /// 􀷱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let airplaneTicket = SFSymbol(rawValue: "airplane.ticket")

    /// 􀷲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let airplaneTicketFill = SFSymbol(rawValue: "airplane.ticket.fill")

    /// 􃎗
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let airplaneUpForward = SFSymbol(rawValue: "airplane.up.forward")

    /// 􃎘
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let airplaneUpForwardApp = SFSymbol(rawValue: "airplane.up.forward.app")

    /// 􃎙
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let airplaneUpForwardAppFill = SFSymbol(rawValue: "airplane.up.forward.app.fill")

    /// 􀸯
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let airplaneUpRight = SFSymbol(rawValue: "airplane.up.right")

    /// 􃋑
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let airplaneUpRightApp = SFSymbol(rawValue: "airplane.up.right.app")

    /// 􃋒
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let airplaneUpRightAppFill = SFSymbol(rawValue: "airplane.up.right.app.fill")

    /// 􃋰
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let airplaneseat = SFSymbol(rawValue: "airplaneseat")

    /// 􂷸
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let appBackgroundDotted = SFSymbol(rawValue: "app.background.dotted")

    /// 􃏞
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let appGrid = SFSymbol(rawValue: "app.grid")

    /// 􃎺
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let appShadow = SFSymbol(rawValue: "app.shadow")

    /// 􃏡
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let appSpecular = SFSymbol(rawValue: "app.specular")

    /// 􃏢
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let appTranslucent = SFSymbol(rawValue: "app.translucent")

    /// 􃁲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let appleBooksPages = SFSymbol(rawValue: "apple.books.pages")

    /// 􃁳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let appleBooksPagesFill = SFSymbol(rawValue: "apple.books.pages.fill")

    /// 􃁬
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let appleClassicalPages = SFSymbol(rawValue: "apple.classical.pages")

    /// 􃁭
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let appleClassicalPagesFill = SFSymbol(rawValue: "apple.classical.pages.fill")

    /// 􃁰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let applePodcastsPages = SFSymbol(rawValue: "apple.podcasts.pages")

    /// 􃁱
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let applePodcastsPagesFill = SFSymbol(rawValue: "apple.podcasts.pages.fill")

    /// 􃊀
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple TV.
    static let appletvBadgeCheckmark = SFSymbol(rawValue: "appletv.badge.checkmark")

    /// 􃊁
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple TV.
    static let appletvBadgeCheckmarkFill = SFSymbol(rawValue: "appletv.badge.checkmark.fill")

    /// 􁰺
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple TV.
    static let appletvBadgeExclamationmark = SFSymbol(rawValue: "appletv.badge.exclamationmark")

    /// 􁰻
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple TV.
    static let appletvBadgeExclamationmarkFill = SFSymbol(rawValue: "appletv.badge.exclamationmark.fill")

    /// 􃊄
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Watch.
    static let applewatchBadgeCheckmark = SFSymbol(rawValue: "applewatch.badge.checkmark")

    /// 􃍤
    /// 2 Localizations, 3 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let appsIpadBadgeCheckmark = SymbolWith1Localization<Rtl>(rawValue: "apps.ipad.badge.checkmark")

    /// 􀯗
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let appsIpadBadgePlus = SFSymbol(rawValue: "apps.ipad.badge.plus")

    /// 􂿬
    /// 2 Localizations, 2 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let appsIpadOnRectanglePortraitDashed = SymbolWith1Localization<Rtl>(rawValue: "apps.ipad.on.rectangle.portrait.dashed")

    /// 􃍢
    /// 2 Localizations, 3 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let appsIphoneBadgeCheckmark = SymbolWith1Localization<Rtl>(rawValue: "apps.iphone.badge.checkmark")

    /// 􃂜
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let aqiMediumGaugeOpen = SFSymbol(rawValue: "aqi.medium.gauge.open")

    /// 􃇖
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let arrowDownCircleBadgePause = SFSymbol(rawValue: "arrow.down.circle.badge.pause")

    /// 􃇗
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let arrowDownCircleBadgePauseFill = SFSymbol(rawValue: "arrow.down.circle.badge.pause.fill")

    /// 􃇚
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let arrowDownCircleBadgeXmark = SFSymbol(rawValue: "arrow.down.circle.badge.xmark")

    /// 􃇛
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let arrowDownCircleBadgeXmarkFill = SFSymbol(rawValue: "arrow.down.circle.badge.xmark.fill")

    /// 􃀩
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let arrowForwardFolder = SymbolWith1Localization<Rtl>(rawValue: "arrow.forward.folder")

    /// 􃀪
    /// 2 Localizations, 3 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let arrowForwardFolderFill = SymbolWith1Localization<Rtl>(rawValue: "arrow.forward.folder.fill")

    /// 􃀧
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let arrowUpFolder = SFSymbol(rawValue: "arrow.up.folder")

    /// 􃀨
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let arrowUpFolderFill = SFSymbol(rawValue: "arrow.up.folder.fill")

    /// 􃀷
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let backpackSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "backpack.sensor.tag.radiowaves.left.and.right")

    /// 􃀸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let backpackSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "backpack.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃍏
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let bedDoubleBadgeCheckmark = SFSymbol(rawValue: "bed.double.badge.checkmark")

    /// 􃍐
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let bedDoubleBadgeCheckmarkFill = SFSymbol(rawValue: "bed.double.badge.checkmark.fill")

    /// 􁈍
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let bellBadgeWaveformSlash = SFSymbol(rawValue: "bell.badge.waveform.slash")

    /// 􁈎
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let bellBadgeWaveformSlashFill = SFSymbol(rawValue: "bell.badge.waveform.slash.fill")

    /// 􃀹
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let bicycleSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "bicycle.sensor.tag.radiowaves.left.and.right")

    /// 􃀺
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let bicycleSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "bicycle.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃑏
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let bookBadgePlus = SFSymbol(rawValue: "book.badge.plus")

    /// 􃑐
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let bookBadgePlusFill = SFSymbol(rawValue: "book.badge.plus.fill")

    /// 􃀱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let briefcaseSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "briefcase.sensor.tag.radiowaves.left.and.right")

    /// 􃀲
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let briefcaseSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "briefcase.sensor.tag.radiowaves.left.and.right.fill")

    /// 􂭿
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let calendarBadge = SFSymbol(rawValue: "calendar.badge")

    /// 􃂂
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let calendarBadgeLock = SFSymbol(rawValue: "calendar.badge.lock")

    /// 􃌄
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let calendarDayTimelineLeadingCircle = SFSymbol(rawValue: "calendar.day.timeline.leading.circle")

    /// 􃌅
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let calendarDayTimelineLeadingCircleFill = SFSymbol(rawValue: "calendar.day.timeline.leading.circle.fill")

    /// 􃋶
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let calendarDayTimelineLeftCircle = SFSymbol(rawValue: "calendar.day.timeline.left.circle")

    /// 􃋷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let calendarDayTimelineLeftCircleFill = SFSymbol(rawValue: "calendar.day.timeline.left.circle.fill")

    /// 􃋸
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let calendarDayTimelineRightCircle = SFSymbol(rawValue: "calendar.day.timeline.right.circle")

    /// 􃋹
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let calendarDayTimelineRightCircleFill = SFSymbol(rawValue: "calendar.day.timeline.right.circle.fill")

    /// 􃌆
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let calendarDayTimelineTrailingCircle = SFSymbol(rawValue: "calendar.day.timeline.trailing.circle")

    /// 􃌇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let calendarDayTimelineTrailingCircleFill = SFSymbol(rawValue: "calendar.day.timeline.trailing.circle.fill")

    /// 􃀻
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let cameraSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "camera.sensor.tag.radiowaves.left.and.right")

    /// 􃀼
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let cameraSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "camera.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃋺
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let cellularbarsCircle = SFSymbol(rawValue: "cellularbars.circle")

    /// 􃋻
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let cellularbarsCircleFill = SFSymbol(rawValue: "cellularbars.circle.fill")

    /// 􃅗
    /// 19 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Bengali
    /// - Chinese
    /// - Gujarati
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Kannada
    /// - Korean
    /// - Malayalam
    /// - Manipuri
    /// - Maranthi
    /// - Oriya
    /// - Punjabi
    /// - Santali
    /// - Sinhala
    /// - Tamil
    /// - Thai
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let characterTextJustify = SymbolWith18Localizations<Ar, Bn, Gu, He, Hi, Ja, Kn, Ko, Ml, Mni, Mr, Or, Pa, Sat, Si, Ta, Th, Zh>(rawValue: "character.text.justify")

    /// 􂿲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let checkmarkApp = SFSymbol(rawValue: "checkmark.app")

    /// 􂿳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let checkmarkAppFill = SFSymbol(rawValue: "checkmark.app.fill")

    /// 􃇽
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let checkmarkArrowTriangleheadClockwise = SFSymbol(rawValue: "checkmark.arrow.trianglehead.clockwise")

    /// 􃋄
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let checkmarkCircleBadgeAirplane = SFSymbol(rawValue: "checkmark.circle.badge.airplane")

    /// 􃋅
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let checkmarkCircleBadgeAirplaneFill = SFSymbol(rawValue: "checkmark.circle.badge.airplane.fill")

    /// 􃈆
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let checkmarkCircleBadgePlus = SFSymbol(rawValue: "checkmark.circle.badge.plus")

    /// 􃈇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let checkmarkCircleBadgePlusFill = SFSymbol(rawValue: "checkmark.circle.badge.plus.fill")

    /// 􃋂
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let checkmarkCircleTrianglebadgeExclamationmarkFill = SFSymbol(rawValue: "checkmark.circle.trianglebadge.exclamationmark.fill")

    /// 􂿪
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let circleGrid2x2TopleftCheckmarkFilled = SFSymbol(rawValue: "circle.grid.2x2.topleft.checkmark.filled")

    /// 􃎷
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let circleOnSquare = SFSymbol(rawValue: "circle.on.square")

    /// 􃏁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let circleOnSquareIntersectionDotted = SFSymbol(rawValue: "circle.on.square.intersection.dotted")

    /// 􃎹
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let circleOnSquareMerge = SFSymbol(rawValue: "circle.on.square.merge")

    /// 􃋐
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let clockArrowTriangleheadClockwiseRotate90PathDotted = SFSymbol(rawValue: "clock.arrow.trianglehead.clockwise.rotate.90.path.dotted")

    /// 􃋌
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let clockBadgeAirplane = SFSymbol(rawValue: "clock.badge.airplane")

    /// 􃋍
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let clockBadgeAirplaneFill = SFSymbol(rawValue: "clock.badge.airplane.fill")

    /// 􃁋
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let coatCircle = SFSymbol(rawValue: "coat.circle")

    /// 􃁌
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let coatCircleFill = SFSymbol(rawValue: "coat.circle.fill")

    /// 􀭈
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let contextualmenuAndPointerArrow = SFSymbol(rawValue: "contextualmenu.and.pointer.arrow")

    /// 􁂨
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let creditcardAndNumbers = SFSymbol(rawValue: "creditcard.and.numbers")

    /// 􃈕
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let creditcardRewards = SFSymbol(rawValue: "creditcard.rewards")

    /// 􃈖
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let creditcardRewardsFill = SFSymbol(rawValue: "creditcard.rewards.fill")

    /// 􃅓
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let cubeCircle = SFSymbol(rawValue: "cube.circle")

    /// 􃅔
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let cubeCircleFill = SFSymbol(rawValue: "cube.circle.fill")

    /// 􃉞
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let desktopcomputerBadgeCheckmark = SFSymbol(rawValue: "desktopcomputer.badge.checkmark")

    /// 􃊆
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let desktopcomputerBadgeShieldCheckmark = SFSymbol(rawValue: "desktopcomputer.badge.shield.checkmark")

    /// 􁣊
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let documentOnTrash = SFSymbol(rawValue: "document.on.trash")

    /// 􁣋
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let documentOnTrashFill = SFSymbol(rawValue: "document.on.trash.fill")

    /// 􀫍
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let dotCircleAndPointerArrow = SFSymbol(rawValue: "dot.circle.and.pointer.arrow")

    /// 􃆮
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let dotCrosshair = SFSymbol(rawValue: "dot.crosshair")

    /// 􁑢
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let dotsAndLineVerticalAndPointerArrowRectangle = SFSymbol(rawValue: "dots.and.line.vertical.and.pointer.arrow.rectangle")

    /// 􃀍
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudLeft = SFSymbol(rawValue: "earbud.left")

    /// 􃀌
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudRight = SFSymbol(rawValue: "earbud.right")

    /// 􃍝
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let earbudsBoneConduction = SFSymbol(rawValue: "earbuds.bone.conduction")

    /// 􃍟
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let earbudsBoneConductionLeft = SFSymbol(rawValue: "earbuds.bone.conduction.left")

    /// 􃍞
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let earbudsBoneConductionRight = SFSymbol(rawValue: "earbuds.bone.conduction.right")

    /// 􃍓
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudsInEar = SFSymbol(rawValue: "earbuds.in.ear")

    /// 􃍕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudsInEarLeft = SFSymbol(rawValue: "earbuds.in.ear.left")

    /// 􃍔
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudsInEarRight = SFSymbol(rawValue: "earbuds.in.ear.right")

    /// 􃍆
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudsStemless = SFSymbol(rawValue: "earbuds.stemless")

    /// 􃍈
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudsStemlessLeft = SFSymbol(rawValue: "earbuds.stemless.left")

    /// 􃍇
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let earbudsStemlessRight = SFSymbol(rawValue: "earbuds.stemless.right")

    /// 􃏝
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let ellipsisCalendar = SFSymbol(rawValue: "ellipsis.calendar")

    /// 􃈗
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let ellipsisCircleBadge = SFSymbol(rawValue: "ellipsis.circle.badge")

    /// 􃈘
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let ellipsisCircleBadgeFill = SFSymbol(rawValue: "ellipsis.circle.badge.fill")

    /// 􃍸
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let envelopeAndHandRaised = SFSymbol(rawValue: "envelope.and.hand.raised")

    /// 􃍹
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let envelopeAndHandRaisedFill = SFSymbol(rawValue: "envelope.and.hand.raised.fill")

    /// 􃈵
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let envelopeBadgeMinus = SFSymbol(rawValue: "envelope.badge.minus")

    /// 􃈶
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let envelopeBadgeMinusFill = SFSymbol(rawValue: "envelope.badge.minus.fill")

    /// 􃈳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let envelopeBadgePlus = SFSymbol(rawValue: "envelope.badge.plus")

    /// 􃈴
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let envelopeBadgePlusFill = SFSymbol(rawValue: "envelope.badge.plus.fill")

    /// 􂀚
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environments = SFSymbol(rawValue: "environments")

    /// 􂀜
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environmentsCircle = SFSymbol(rawValue: "environments.circle")

    /// 􂀝
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environmentsCircleFill = SFSymbol(rawValue: "environments.circle.fill")

    /// 􀬮
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environmentsFill = SFSymbol(rawValue: "environments.fill")

    /// 􂁚
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environmentsSlash = SFSymbol(rawValue: "environments.slash")

    /// 􂀞
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environmentsSlashCircle = SFSymbol(rawValue: "environments.slash.circle")

    /// 􂀟
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environmentsSlashCircleFill = SFSymbol(rawValue: "environments.slash.circle.fill")

    /// 􁦅
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Environments feature.
    static let environmentsSlashFill = SFSymbol(rawValue: "environments.slash.fill")

    /// 􃁕
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let eraserBadgeXmark = SFSymbol(rawValue: "eraser.badge.xmark")

    /// 􃁖
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let eraserBadgeXmarkFill = SFSymbol(rawValue: "eraser.badge.xmark.fill")

    /// 􃁙
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let eraserSlash = SFSymbol(rawValue: "eraser.slash")

    /// 􃁚
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let eraserSlashFill = SFSymbol(rawValue: "eraser.slash.fill")

    /// 􃁗
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let eraserTrianglebadgeExclamationmark = SFSymbol(rawValue: "eraser.trianglebadge.exclamationmark")

    /// 􃁘
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let eraserTrianglebadgeExclamationmarkFill = SFSymbol(rawValue: "eraser.trianglebadge.exclamationmark.fill")

    /// 􂽁
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let eyeHalfClosed = SFSymbol(rawValue: "eye.half.closed")

    /// 􂽂
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let eyeHalfClosedFill = SFSymbol(rawValue: "eye.half.closed.fill")

    /// 􃄻
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let fanBadgeArrowUpAndDownAndArrowLeftAndRight = SFSymbol(rawValue: "fan.badge.arrow.up.and.down.and.arrow.left.and.right")

    /// 􃄼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let fanBadgeArrowUpAndDownAndArrowLeftAndRightFill = SFSymbol(rawValue: "fan.badge.arrow.up.and.down.and.arrow.left.and.right.fill")

    /// 􃂢
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let fanCircle = SFSymbol(rawValue: "fan.circle")

    /// 􃂣
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let fanCircleFill = SFSymbol(rawValue: "fan.circle.fill")

    /// 􃂞
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let fanGaugeOpen = SFSymbol(rawValue: "fan.gauge.open")

    /// 􃅃
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let figureSeatedSideLeftAirDistributionIndirect = SFSymbol(rawValue: "figure.seated.side.left.air.distribution.indirect")

    /// 􃄿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let figureSeatedSideLeftAirDistributionLowerAngledAndUpperAngled = SFSymbol(rawValue: "figure.seated.side.left.air.distribution.lower.angled.and.upper.angled")

    /// 􃅁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let figureSeatedSideLeftAirDistributionUpperAngledAndDottedlineAndLowerAngled = SFSymbol(rawValue: "figure.seated.side.left.air.distribution.upper.angled.and.dottedline.and.lower.angled")

    /// 􃅄
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let figureSeatedSideRightAirDistributionIndirect = SFSymbol(rawValue: "figure.seated.side.right.air.distribution.indirect")

    /// 􃅀
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let figureSeatedSideRightAirDistributionLowerAngledAndUpperAngled = SFSymbol(rawValue: "figure.seated.side.right.air.distribution.lower.angled.and.upper.angled")

    /// 􃅂
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let figureSeatedSideRightAirDistributionUpperAngledAndDottedlineAndLowerAngled = SFSymbol(rawValue: "figure.seated.side.right.air.distribution.upper.angled.and.dottedline.and.lower.angled")

    /// 􃌐
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let figureSeatedSideRightChildLap = SFSymbol(rawValue: "figure.seated.side.right.child.lap")

    /// 􃋱
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let figureWalkSuitcaseRolling = SFSymbol(rawValue: "figure.walk.suitcase.rolling")

    /// 􃋲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let figureWalkSuitcaseRollingCircle = SFSymbol(rawValue: "figure.walk.suitcase.rolling.circle")

    /// 􃋳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let figureWalkSuitcaseRollingCircleFill = SFSymbol(rawValue: "figure.walk.suitcase.rolling.circle.fill")

    /// 􀯪
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let filemenuAndPointerArrow = SymbolWith1Localization<Rtl>(rawValue: "filemenu.and.pointer.arrow")

    /// 􀥯
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple's Finder app.
    static let finder = SFSymbol(rawValue: "finder")

    /// 􃂝
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let flameGaugeOpen = SFSymbol(rawValue: "flame.gauge.open")

    /// 􃄹
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let fuelpumpThermometer = SFSymbol(rawValue: "fuelpump.thermometer")

    /// 􃄺
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let fuelpumpThermometerFill = SFSymbol(rawValue: "fuelpump.thermometer.fill")

    /// 􃊊
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let gaugeChartLefthalfRighthalf = SFSymbol(rawValue: "gauge.chart.lefthalf.righthalf")

    /// 􃊋
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let gaugeChartLeftthirdTopthirdRightthird = SFSymbol(rawValue: "gauge.chart.leftthird.topthird.rightthird")

    /// 􃂄
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let gaugeOpen = SFSymbol(rawValue: "gauge.open")

    /// 􂼑
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let gaugeOpenRighthalfDottedWithNeedleAndArrowTriangleheadBackward = SFSymbol(rawValue: "gauge.open.righthalf.dotted.with.needle.and.arrow.trianglehead.backward")

    /// 􃁔
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let globeFill = SFSymbol(rawValue: "globe.fill")

    /// 􃈟
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let graph2d = SFSymbol(rawValue: "graph.2d")

    /// 􃈠
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let graph3d = SFSymbol(rawValue: "graph.3d")

    /// 􃐉
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let guidepointHorizontal = SFSymbol(rawValue: "guidepoint.horizontal")

    /// 􃂲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let guidepointVerticalArrowtriangleForward = SFSymbol(rawValue: "guidepoint.vertical.arrowtriangle.forward")

    /// 􃂳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let guidepointVerticalNumbers = SFSymbol(rawValue: "guidepoint.vertical.numbers")

    /// 􃀽
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let handbagSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "handbag.sensor.tag.radiowaves.left.and.right")

    /// 􃀾
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let handbagSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "handbag.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃍅
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let headphonesOverEar = SFSymbol(rawValue: "headphones.over.ear")

    /// 􃀿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let headphonesSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "headphones.sensor.tag.radiowaves.left.and.right")

    /// 􃁀
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let headphonesSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "headphones.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃂡
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let heartGaugeOpen = SFSymbol(rawValue: "heart.gauge.open")

    /// 􃂤
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let heatWavesCircle = SFSymbol(rawValue: "heat.waves.circle")

    /// 􃂥
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let heatWavesCircleFill = SFSymbol(rawValue: "heat.waves.circle.fill")

    /// 􃂟
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let heatWavesGaugeOpen = SFSymbol(rawValue: "heat.waves.gauge.open")

    /// 􃉰
    /// 2 Localizations, 3 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod.
    static let homepodBadgeCheckmark = SymbolWith1Localization<Rtl>(rawValue: "homepod.badge.checkmark")

    /// 􃉱
    /// 2 Localizations, 3 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod.
    static let homepodBadgeCheckmarkFill = SymbolWith1Localization<Rtl>(rawValue: "homepod.badge.checkmark.fill")

    /// 􀻹
    /// 2 Localizations, 2 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini and Apple TV.
    static let homepodMiniAndAppletv = SymbolWith1Localization<Rtl>(rawValue: "homepod.mini.and.appletv")

    /// 􀻺
    /// 2 Localizations, 2 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini and Apple TV.
    static let homepodMiniAndAppletvFill = SymbolWith1Localization<Rtl>(rawValue: "homepod.mini.and.appletv.fill")

    /// 􃉸
    /// 2 Localizations, 3 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let homepodMiniBadgeCheckmark = SymbolWith1Localization<Rtl>(rawValue: "homepod.mini.badge.checkmark")

    /// 􃉹
    /// 2 Localizations, 3 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let homepodMiniBadgeCheckmarkFill = SymbolWith1Localization<Rtl>(rawValue: "homepod.mini.badge.checkmark.fill")

    /// 􂇗
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let hourglassBadgeLock = SFSymbol(rawValue: "hourglass.badge.lock")

    /// 􀚏
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iCloud service.
    static let icloudDashed = SFSymbol(rawValue: "icloud.dashed")

    /// 􃐸
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let insetFilledBottomleadingBottomtrailingRectangle = SFSymbol(rawValue: "inset.filled.bottomleading.bottomtrailing.rectangle")

    /// 􃐷
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let insetFilledBottomleftBottomrightRectangle = SFSymbol(rawValue: "inset.filled.bottomleft.bottomright.rectangle")

    /// 􃇐
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let insetFilledLeftthirdMiddlethirdRightthirdRectangle = SFSymbol(rawValue: "inset.filled.leftthird.middlethird.rightthird.rectangle")

    /// 􂖡
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let insetFilledPano = SFSymbol(rawValue: "inset.filled.pano")

    /// 􂇕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let insetFilledRectangleAndPointerArrow = SFSymbol(rawValue: "inset.filled.rectangle.and.pointer.arrow")

    /// 􃈃
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let insetFilledTopthirdMiddlethirdBottomthirdRectangle = SFSymbol(rawValue: "inset.filled.topthird.middlethird.bottomthird.rectangle")

    /// 􃉖
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadBadgeCheckmark = SFSymbol(rawValue: "ipad.badge.checkmark")

    /// 􃏟
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadGen1CropHomebuttonCircle = SFSymbol(rawValue: "ipad.gen1.crop.homebutton.circle")

    /// 􁣵
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadGen1Sizes = SFSymbol(rawValue: "ipad.gen1.sizes")

    /// 􃉌
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadGen2Sizes = SFSymbol(rawValue: "ipad.gen2.sizes")

    /// 􃉔
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneBadgeCheckmark = SFSymbol(rawValue: "iphone.badge.checkmark")

    /// 􃂴
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneGen1CropHomebuttonCircle = SFSymbol(rawValue: "iphone.gen1.crop.homebutton.circle")

    /// 􃉈
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneGen1Sizes = SFSymbol(rawValue: "iphone.gen1.sizes")

    /// 􁣳
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneGen2Sizes = SFSymbol(rawValue: "iphone.gen2.sizes")

    /// 􃉊
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneGen3Sizes = SFSymbol(rawValue: "iphone.gen3.sizes")

    /// 􂤨
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let iphonePatternDiagonalline = SFSymbol(rawValue: "iphone.pattern.diagonalline")

    /// 􂿥
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let iphonePatternDiagonallineOnRectanglePortraitDashed = SFSymbol(rawValue: "iphone.pattern.diagonalline.on.rectangle.portrait.dashed")

    /// 􃁉
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let jacketCircle = SFSymbol(rawValue: "jacket.circle")

    /// 􃁊
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let jacketCircleFill = SFSymbol(rawValue: "jacket.circle.fill")

    /// 􃁁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let jacketSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "jacket.sensor.tag.radiowaves.left.and.right")

    /// 􃁂
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let jacketSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "jacket.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃁇
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keyCircle = SFSymbol(rawValue: "key.circle")

    /// 􃁈
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let keyCircleFill = SFSymbol(rawValue: "key.circle.fill")

    /// 􃀳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keySensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "key.sensor.tag.radiowaves.left.and.right")

    /// 􃀴
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let keySensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "key.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃇞
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keyShield = SFSymbol(rawValue: "key.shield")

    /// 􃇟
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let keyShieldFill = SFSymbol(rawValue: "key.shield.fill")

    /// 􃉘
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let laptopcomputerBadgeCheckmark = SFSymbol(rawValue: "laptopcomputer.badge.checkmark")

    /// 􀫱
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let lineDiagonalTriangleheadUpRight = SFSymbol(rawValue: "line.diagonal.trianglehead.up.right")

    /// 􃏠
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let lineDiagonalTriangleheadUpRightLeftDown = SFSymbol(rawValue: "line.diagonal.trianglehead.up.right.left.down")

    /// 􃋮
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let linesMeasurementHorizontalAlignedBottom = SFSymbol(rawValue: "lines.measurement.horizontal.aligned.bottom")

    /// 􃈩
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let listDashHeaderRectangleFill = SFSymbol(rawValue: "list.dash.header.rectangle.fill")

    /// 􃍰
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let lockBadgeCheckmark = SFSymbol(rawValue: "lock.badge.checkmark")

    /// 􃍱
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let lockBadgeCheckmarkFill = SFSymbol(rawValue: "lock.badge.checkmark.fill")

    /// 􃍴
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let lockBadgeXmark = SFSymbol(rawValue: "lock.badge.xmark")

    /// 􃍵
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let lockBadgeXmarkFill = SFSymbol(rawValue: "lock.badge.xmark.fill")

    /// 􃊿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let lockHeart = SFSymbol(rawValue: "lock.heart")

    /// 􃋀
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let lockHeartFill = SFSymbol(rawValue: "lock.heart.fill")

    /// 􃐭
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let lockRectangleDashed = SFSymbol(rawValue: "lock.rectangle.dashed")

    /// 􃉚
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s MacBook.
    static let macbookBadgeCheckmark = SFSymbol(rawValue: "macbook.badge.checkmark")

    /// 􃊈
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s MacBook.
    static let macbookBadgeShieldCheckmark = SFSymbol(rawValue: "macbook.badge.shield.checkmark")

    /// 􃉏
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s MacBook.
    static let macbookGen1Sizes = SFSymbol(rawValue: "macbook.gen1.sizes")

    /// 􃉐
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s MacBook.
    static let macbookGen2Sizes = SFSymbol(rawValue: "macbook.gen2.sizes")

    /// 􃉎
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s MacBook.
    static let macbookSizes = SFSymbol(rawValue: "macbook.sizes")

    /// 􃉛
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s MacBook.
    static let macbookTrianglebadgeExclamationmark = SFSymbol(rawValue: "macbook.trianglebadge.exclamationmark")

    /// 􃉨
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static let macminiBadgeCheckmark = SFSymbol(rawValue: "macmini.badge.checkmark")

    /// 􃉩
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static let macminiBadgeCheckmarkFill = SFSymbol(rawValue: "macmini.badge.checkmark.fill")

    /// 􃉠
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac Pro.
    static let macproGen3BadgeCkeckmark = SFSymbol(rawValue: "macpro.gen3.badge.ckeckmark")

    /// 􃉡
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac Pro.
    static let macproGen3BadgeCkeckmarkFill = SFSymbol(rawValue: "macpro.gen3.badge.ckeckmark.fill")

    /// 􃉤
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac Studio.
    static let macstudioBadgeCheckmark = SFSymbol(rawValue: "macstudio.badge.checkmark")

    /// 􃉥
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac Studio.
    static let macstudioBadgeCheckmarkFill = SFSymbol(rawValue: "macstudio.badge.checkmark.fill")

    /// 􁝸
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let macwindowAndPointerArrow = SymbolWith1Localization<Rtl>(rawValue: "macwindow.and.pointer.arrow")

    /// 􃇼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let minusArrowTriangleheadClockwise = SFSymbol(rawValue: "minus.arrow.trianglehead.clockwise")

    /// 􃋯
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let minusPlusLinesMeasurementHorizontalAlignedBottom = SFSymbol(rawValue: "minus.plus.lines.measurement.horizontal.aligned.bottom")

    /// 􃃂
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let musicNoteArrowTriangleheadClockwise = SFSymbol(rawValue: "music.note.arrow.trianglehead.clockwise")

    /// 􃑓
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let musicNoteSlash = SFSymbol(rawValue: "music.note.slash")

    /// 􃐹
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let musicNoteSquareStack = SFSymbol(rawValue: "music.note.square.stack")

    /// 􃐺
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let musicNoteSquareStackFill = SFSymbol(rawValue: "music.note.square.stack.fill")

    /// 􃁮
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let musicPages = SFSymbol(rawValue: "music.pages")

    /// 􃁯
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let musicPagesFill = SFSymbol(rawValue: "music.pages.fill")

    /// 􀧵
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let padHeader = SFSymbol(rawValue: "pad.header")

    /// 􀠣
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let paintBucketClassic = SFSymbol(rawValue: "paint.bucket.classic")

    /// 􂣑
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let person2Badge = SFSymbol(rawValue: "person.2.badge")

    /// 􂣒
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let person2BadgeFill = SFSymbol(rawValue: "person.2.badge.fill")

    /// 􃂇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let personCropCircleBadgeEllipsis = SFSymbol(rawValue: "person.crop.circle.badge.ellipsis")

    /// 􃂈
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let personCropCircleBadgeEllipsisFill = SFSymbol(rawValue: "person.crop.circle.badge.ellipsis.fill")

    /// 􃈮
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Audio.
    static let personSpatialaudio3dFill = SFSymbol(rawValue: "person.spatialaudio.3d.fill")

    /// 􁀨
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Audio.
    static let personSpatialaudioFill = SFSymbol(rawValue: "person.spatialaudio.fill")

    /// 􃈭
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Audio.
    static let personSpatialaudioStereo3dFill = SFSymbol(rawValue: "person.spatialaudio.stereo.3d.fill")

    /// 􁀧
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Audio.
    static let personSpatialaudioStereoFill = SFSymbol(rawValue: "person.spatialaudio.stereo.fill")

    /// 􃌑
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let petCarrier = SFSymbol(rawValue: "pet.carrier")

    /// 􃎤
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let petCarrierCircle = SFSymbol(rawValue: "pet.carrier.circle")

    /// 􃎥
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let petCarrierCircleFill = SFSymbol(rawValue: "pet.carrier.circle.fill")

    /// 􃌒
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let petCarrierFill = SFSymbol(rawValue: "pet.carrier.fill")

    /// 􃂓
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let phonePause = SFSymbol(rawValue: "phone.pause")

    /// 􃂕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let phonePauseCircle = SFSymbol(rawValue: "phone.pause.circle")

    /// 􃂖
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let phonePauseCircleFill = SFSymbol(rawValue: "phone.pause.circle.fill")

    /// 􃂔
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let phonePauseFill = SFSymbol(rawValue: "phone.pause.fill")

    /// 􃄤
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let playDiamond = SFSymbol(rawValue: "play.diamond")

    /// 􃄥
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let playDiamondFill = SFSymbol(rawValue: "play.diamond.fill")

    /// 􃇿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let plusArrowTriangleheadCounterclockwise = SFSymbol(rawValue: "plus.arrow.trianglehead.counterclockwise")

    /// 􃁴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let plusCapsule = SFSymbol(rawValue: "plus.capsule")

    /// 􃁵
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let plusCapsuleFill = SFSymbol(rawValue: "plus.capsule.fill")

    /// 􀫌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let pointerArrow = SFSymbol(rawValue: "pointer.arrow")

    /// 􀮐
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let pointerArrowAndSquareOnSquareDashed = SFSymbol(rawValue: "pointer.arrow.and.square.on.square.dashed")

    /// 􀭆
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let pointerArrowClick = SFSymbol(rawValue: "pointer.arrow.click")

    /// 􀭇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let pointerArrowClick2 = SFSymbol(rawValue: "pointer.arrow.click.2")

    /// 􀮴
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let pointerArrowClickBadgeClock = SFSymbol(rawValue: "pointer.arrow.click.badge.clock")

    /// 􀣠
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let pointerArrowMotionlines = SFSymbol(rawValue: "pointer.arrow.motionlines")

    /// 􀣡
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let pointerArrowMotionlinesClick = SFSymbol(rawValue: "pointer.arrow.motionlines.click")

    /// 􀇰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let pointerArrowRays = SFSymbol(rawValue: "pointer.arrow.rays")

    /// 􁷁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let pointerArrowSlash = SFSymbol(rawValue: "pointer.arrow.slash")

    /// 􁷂
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let pointerArrowSlashSquare = SFSymbol(rawValue: "pointer.arrow.slash.square")

    /// 􁷃
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let pointerArrowSlashSquareFill = SFSymbol(rawValue: "pointer.arrow.slash.square.fill")

    /// 􀭅
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let pointerArrowSquare = SFSymbol(rawValue: "pointer.arrow.square")

    /// 􁚀
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let pointerArrowSquareFill = SFSymbol(rawValue: "pointer.arrow.square.fill")

    /// 􃑊
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let rectangle3GroupDashed = SFSymbol(rawValue: "rectangle.3.group.dashed")

    /// 􃈑
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let rectangleStackSlash = SFSymbol(rawValue: "rectangle.stack.slash")

    /// 􃈒
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let rectangleStackSlashFill = SFSymbol(rawValue: "rectangle.stack.slash.fill")

    /// 􂻛
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let repeatBadgeXmark = SFSymbol(rawValue: "repeat.badge.xmark")

    /// 􃊍
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let ring = SFSymbol(rawValue: "ring")

    /// 􃊌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let ringDashed = SFSymbol(rawValue: "ring.dashed")

    /// 􃆲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let sensorRadiowavesLeftAndRight = SFSymbol(rawValue: "sensor.radiowaves.left.and.right")

    /// 􃆳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let sensorRadiowavesLeftAndRightFill = SFSymbol(rawValue: "sensor.radiowaves.left.and.right.fill")

    /// 􃎢
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let serviceDog = SFSymbol(rawValue: "service.dog")

    /// 􃎣
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let serviceDogFill = SFSymbol(rawValue: "service.dog.fill")

    /// 􀫛
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Siri.
    static let siri = SFSymbol(rawValue: "siri")

    /// 􃁣
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let sliderHorizontalBelowCircleLefthalfFilled = SFSymbol(rawValue: "slider.horizontal.below.circle.lefthalf.filled")

    /// 􃁤
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let sliderHorizontalBelowCircleLefthalfFilledInverse = SFSymbol(rawValue: "slider.horizontal.below.circle.lefthalf.filled.inverse")

    /// 􃁥
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let sliderHorizontalBelowCircleRighthalfFilled = SFSymbol(rawValue: "slider.horizontal.below.circle.righthalf.filled")

    /// 􃁦
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let sliderHorizontalBelowCircleRighthalfFilledInverse = SFSymbol(rawValue: "slider.horizontal.below.circle.righthalf.filled.inverse")

    /// 􃈰
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let sparkles2 = SFSymbol(rawValue: "sparkles.2")

    /// 􂊑
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Scene feature.
    static let spatialCapture = SFSymbol(rawValue: "spatial.capture")

    /// 􂊒
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Scene feature.
    static let spatialCaptureFill = SFSymbol(rawValue: "spatial.capture.fill")

    /// 􂊓
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Scene feature.
    static let spatialCaptureOnHexagon = SFSymbol(rawValue: "spatial.capture.on.hexagon")

    /// 􂊔
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Scene feature.
    static let spatialCaptureOnHexagonFill = SFSymbol(rawValue: "spatial.capture.on.hexagon.fill")

    /// 􂪙
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Scene feature.
    static let spatialCaptureSlash = SFSymbol(rawValue: "spatial.capture.slash")

    /// 􂪚
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Spatial Scene feature.
    static let spatialCaptureSlashFill = SFSymbol(rawValue: "spatial.capture.slash.fill")

    /// 􃊺
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let speakerTrianglebadgeExclamationmark = SFSymbol(rawValue: "speaker.trianglebadge.exclamationmark")

    /// 􃊻
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let speakerTrianglebadgeExclamationmarkFill = SFSymbol(rawValue: "speaker.trianglebadge.exclamationmark.fill")

    /// 􁟀
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let steeringwheelBadgeLock = SFSymbol(rawValue: "steeringwheel.badge.lock")

    /// 􃐋
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let strikethroughDouble = SFSymbol(rawValue: "strikethrough.double")

    /// 􃁅
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseCircle = SFSymbol(rawValue: "suitcase.circle")

    /// 􃁆
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let suitcaseCircleFill = SFSymbol(rawValue: "suitcase.circle.fill")

    /// 􃌈
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseRollingAndFilm = SFSymbol(rawValue: "suitcase.rolling.and.film")

    /// 􃌌
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseRollingAndFilmCircle = SFSymbol(rawValue: "suitcase.rolling.and.film.circle")

    /// 􃌍
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let suitcaseRollingAndFilmCircleFill = SFSymbol(rawValue: "suitcase.rolling.and.film.circle.fill")

    /// 􃌉
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseRollingAndFilmFill = SFSymbol(rawValue: "suitcase.rolling.and.film.fill")

    /// 􃋕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseRollingAndSuitcase = SFSymbol(rawValue: "suitcase.rolling.and.suitcase")

    /// 􃋗
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseRollingAndSuitcaseCircle = SFSymbol(rawValue: "suitcase.rolling.and.suitcase.circle")

    /// 􃋘
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let suitcaseRollingAndSuitcaseCircleFill = SFSymbol(rawValue: "suitcase.rolling.and.suitcase.circle.fill")

    /// 􃋖
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseRollingAndSuitcaseFill = SFSymbol(rawValue: "suitcase.rolling.and.suitcase.fill")

    /// 􃋓
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suitcaseRollingCircle = SFSymbol(rawValue: "suitcase.rolling.circle")

    /// 􃋔
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let suitcaseRollingCircleFill = SFSymbol(rawValue: "suitcase.rolling.circle.fill")

    /// 􃐯
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let textBelowFolder = SFSymbol(rawValue: "text.below.folder")

    /// 􃐰
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let textBelowFolderFill = SFSymbol(rawValue: "text.below.folder.fill")

    /// 􀓕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let textPadHeader = SFSymbol(rawValue: "text.pad.header")

    /// 􃀑
    /// 2 Localizations, 3 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let textPadHeaderBadgeClock = SymbolWith1Localization<Rtl>(rawValue: "text.pad.header.badge.clock")

    /// 􀣙
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor
    /// - Hierarchical
    static let textPadHeaderBadgePlus = SFSymbol(rawValue: "text.pad.header.badge.plus")

    /// 􃐵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let textRectangle = SFSymbol(rawValue: "text.rectangle")

    /// 􃐶
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let textRectangleFill = SFSymbol(rawValue: "text.rectangle.fill")

    /// 􃆭
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let textSquareFilled = SFSymbol(rawValue: "text.square.filled")

    /// 􃂠
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let thermometerGaugeOpen = SFSymbol(rawValue: "thermometer.gauge.open")

    /// 􂿩
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let thermometerTirepressure = SFSymbol(rawValue: "thermometer.tirepressure")

    /// 􃐍
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let thermometerVariableBadgeClock = SFSymbol(rawValue: "thermometer.variable.badge.clock")

    /// 􃐎
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let thermometerVariableBadgePlay = SFSymbol(rawValue: "thermometer.variable.badge.play")

    /// 􃀜
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let tramCard = SFSymbol(rawValue: "tram.card")

    /// 􃀝
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let tramCardFill = SFSymbol(rawValue: "tram.card.fill")

    /// 􃃬
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let trayBadge = SFSymbol(rawValue: "tray.badge")

    /// 􃃭
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let trayBadgeFill = SFSymbol(rawValue: "tray.badge.fill")

    /// 􃁍
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let umbrellaCircle = SFSymbol(rawValue: "umbrella.circle")

    /// 􃁎
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let umbrellaCircleFill = SFSymbol(rawValue: "umbrella.circle.fill")

    /// 􃂛
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let umbrellaGaugeOpen = SFSymbol(rawValue: "umbrella.gauge.open")

    /// 􃁃
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let umbrellaSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "umbrella.sensor.tag.radiowaves.left.and.right")

    /// 􃁄
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let umbrellaSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "umbrella.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃐊
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let underlineDouble = SFSymbol(rawValue: "underline.double")

    /// 􃅅
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let ventHeatWavesUpward = SFSymbol(rawValue: "vent.heat.waves.upward")

    /// 􃉬
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Vision Pro.
    static let visionProBadgeCheckmark = SFSymbol(rawValue: "vision.pro.badge.checkmark")

    /// 􃉭
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Vision Pro.
    static let visionProBadgeCheckmarkFill = SFSymbol(rawValue: "vision.pro.badge.checkmark.fill")

    /// 􃀵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let walletSensorTagRadiowavesLeftAndRight = SFSymbol(rawValue: "wallet.sensor.tag.radiowaves.left.and.right")

    /// 􃀶
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let walletSensorTagRadiowavesLeftAndRightFill = SFSymbol(rawValue: "wallet.sensor.tag.radiowaves.left.and.right.fill")

    /// 􃊸
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let waveformLow = SFSymbol(rawValue: "waveform.low")

    /// 􃊹
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let waveformMid = SFSymbol(rawValue: "waveform.mid")

    /// 􃋈
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let xmarkCircleBadgeAirplane = SFSymbol(rawValue: "xmark.circle.badge.airplane")

    /// 􃋉
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let xmarkCircleBadgeAirplaneFill = SFSymbol(rawValue: "xmark.circle.badge.airplane.fill")
}
