// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 6.2 Symbols
@available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *)
public extension SFSymbol {
    /// No preview available
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen4 = SFSymbol(rawValue: "airpods.gen4")

    /// No preview available
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen4ChargingcaseWireless = SFSymbol(rawValue: "airpods.gen4.chargingcase.wireless")

    /// No preview available
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen4ChargingcaseWirelessFill = SFSymbol(rawValue: "airpods.gen4.chargingcase.wireless.fill")

    /// No preview available
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen4Left = SFSymbol(rawValue: "airpods.gen4.left")

    /// No preview available
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen4Right = SFSymbol(rawValue: "airpods.gen4.right")

    /// No preview available
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Writing Tools.
    static let appleWritingTools = SFSymbol(rawValue: "apple.writing.tools")

    /// No preview available
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static let exclamationmarkTriangleTextPage = SymbolWith1Localization<Rtl>(rawValue: "exclamationmark.triangle.text.page")

    /// No preview available
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static let exclamationmarkTriangleTextPageFill = SymbolWith1Localization<Rtl>(rawValue: "exclamationmark.triangle.text.page.fill")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let figureSeatedSideLeftAirDistributionUpperAndMiddleAndLower = SFSymbol(rawValue: "figure.seated.side.left.air.distribution.upper.and.middle.and.lower")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let figureSeatedSideRightAirDistributionUpperAndMiddleAndLower = SFSymbol(rawValue: "figure.seated.side.right.air.distribution.upper.and.middle.and.lower")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let headphonesDots = SFSymbol(rawValue: "headphones.dots")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let infoTriangle = SFSymbol(rawValue: "info.triangle")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let infoTriangleFill = SFSymbol(rawValue: "info.triangle.fill")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let insetFilledRectangleAndPersonFilledCircle = SFSymbol(rawValue: "inset.filled.rectangle.and.person.filled.circle")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let insetFilledRectangleAndPersonFilledCircleFill = SFSymbol(rawValue: "inset.filled.rectangle.and.person.filled.circle.fill")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let receipt = SFSymbol(rawValue: "receipt")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let receiptFill = SFSymbol(rawValue: "receipt.fill")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let wandAndOutline = SFSymbol(rawValue: "wand.and.outline")

    /// No preview available
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let wandAndOutlineInverse = SFSymbol(rawValue: "wand.and.outline.inverse")
}
