// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 3.1 Symbols
@available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
public extension SFSymbol {
    /// 􁉘
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let boltRingClosed = SFSymbol(rawValue: "bolt.ring.closed")

    /// 􁋂
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let platterFilledBottomAndArrowDownIphone = SFSymbol(rawValue: "platter.filled.bottom.and.arrow.down.iphone")

    /// 􁋀
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let platterFilledBottomIphone = SFSymbol(rawValue: "platter.filled.bottom.iphone")

    /// 􁋁
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let platterFilledTopAndArrowUpIphone = SFSymbol(rawValue: "platter.filled.top.and.arrow.up.iphone")

    /// 􁊿
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let platterFilledTopIphone = SFSymbol(rawValue: "platter.filled.top.iphone")

    /// 􁋜
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let square3Layers3dDownBackward = SFSymbol(rawValue: "square.3.layers.3d.down.backward")

    /// 􁋛
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let square3Layers3dDownForward = SFSymbol(rawValue: "square.3.layers.3d.down.forward")

    /// 􁉼
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let square3Layers3dDownLeft = SFSymbol(rawValue: "square.3.layers.3d.down.left")

    /// 􁉽
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// Localizations:
    /// - Standard
    static let square3Layers3dDownRight = SFSymbol(rawValue: "square.3.layers.3d.down.right")

    /// 􁉀
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Localizations:
    /// - Standard
    static let textJustifyLeading = SFSymbol(rawValue: "text.justify.leading")

    /// 􀌄
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Localizations:
    /// - Standard
    static let textJustifyLeft = SFSymbol(rawValue: "text.justify.left")

    /// 􀌅
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Localizations:
    /// - Standard
    static let textJustifyRight = SFSymbol(rawValue: "text.justify.right")

    /// 􁉁
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// Localizations:
    /// - Standard
    static let textJustifyTrailing = SFSymbol(rawValue: "text.justify.trailing")
}
