// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 5.4 Symbols
@available(iOS 17.6, macOS 14.6, tvOS 17.6, watchOS 10.6, visionOS 1.3, *)
public extension SFSymbol {
    /// 􂟊
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Pill.
    static var beatsPill: SFSymbol { .init(rawValue: "beats.pill") }

    /// 􂟋
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Pill.
    static var beatsPillFill: SFSymbol { .init(rawValue: "beats.pill.fill") }

    /// 􂟌
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Solo Buds.
    static var beatsSolobuds: SFSymbol { .init(rawValue: "beats.solobuds") }

    /// 􂟏
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Solo Buds case.
    static var beatsSolobudsChargingcase: SFSymbol { .init(rawValue: "beats.solobuds.chargingcase") }

    /// 􂟐
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Solo Buds case.
    static var beatsSolobudsChargingcaseFill: SFSymbol { .init(rawValue: "beats.solobuds.chargingcase.fill") }

    /// 􂟎
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Solo Buds.
    static var beatsSolobudsLeft: SFSymbol { .init(rawValue: "beats.solobuds.left") }

    /// 􂟍
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Solo Buds.
    static var beatsSolobudsRight: SFSymbol { .init(rawValue: "beats.solobuds.right") }
}
