// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4, visionOS 1.0, *)
extension SFSymbol {
    internal static var localizationsAvailableSince4_2: [SFSymbol : Set<Localization>] {
        [
            _1Lane: [.ar, .hi],
            _10Lane: [.ar, .hi],
            _11Lane: [.ar, .hi],
            _12Lane: [.ar, .hi],
            _2Lane: [.ar, .hi],
            _3Lane: [.ar, .hi],
            _4Lane: [.ar, .hi],
            _5Lane: [.ar, .hi],
            _6Lane: [.ar, .hi],
            _7Lane: [.ar, .hi],
            _8Lane: [.ar, .hi],
            _9Lane: [.ar, .hi],
            axle2: [],
            axle2FrontAndRearEngaged: [],
            axle2FrontEngaged: [],
            axle2RearEngaged: [],
            beatsPowerbeatsLeft: [],
            beatsPowerbeatsRight: [],
            beatsPowerbeats3Left: [],
            beatsPowerbeats3Right: []
        ]
    }

    internal static var symbolsDeprecatedSince4_2: Set<SFSymbol> {
        [
            axel2,
            axel2FrontAndRearEngaged,
            axel2FrontEngaged,
            axel2RearEngaged
        ]
    }
}
