// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
extension SFSymbol {
    internal static var symbolsAvailableSince2_1: Set<SFSymbol> {
        [
            aqiHigh,
            aqiLow,
            aqiMedium,
            brazilianrealsignCircle,
            brazilianrealsignCircleFill,
            brazilianrealsignSquare,
            brazilianrealsignSquareFill,
            cartCircle,
            cartCircleFill,
            character,
            characterBookClosed,
            characterBookClosedFill,
            clockArrow2Circlepath,
            directcurrent,
            exclamationmarkApplewatch,
            infinityCircle,
            infinityCircleFill,
            ipadBadgePlay,
            ipadHomebuttonBadgePlay,
            ipadHomebuttonLandscapeBadgePlay,
            ipadLandscapeBadgePlay,
            iphoneBadgePlay,
            iphoneHomebuttonBadgePlay,
            iphoneHomebuttonLandscape,
            iphoneLandscape,
            ipodtouchLandscape,
            lockApplewatch,
            photoTv,
            playTv,
            playTvFill,
            rectangleBadgePersonCrop,
            rectangleFillBadgePersonCrop,
            rectangleTopthirdInset,
            repeat1Circle,
            repeat1CircleFill,
            repeatCircle,
            repeatCircleFill,
            shieldCheckerboard,
            shuffleCircle,
            shuffleCircleFill,
            textformatSizeLarger,
            textformatSizeSmaller,
            torus,
            tvAndMediabox
        ]
    }

    internal static var symbolsDeprecatedSince2_1: Set<SFSymbol> {
        [
            a,
            aBookClosed,
            aBookClosedFill
        ]
    }
}
