// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 6.1 Symbols
@available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *)
public extension SFSymbol {
    /// 􂶠
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let boltHouse = SFSymbol(rawValue: "bolt.house")

    /// 􂶡
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let boltHouseFill = SFSymbol(rawValue: "bolt.house.fill")

    /// 􂷔
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    static let cableConnectorVideo = SFSymbol(rawValue: "cable.connector.video")

    /// 􂴾
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopRadiowaves2FrontLeftFrontFrontRight = SFSymbol(rawValue: "car.top.radiowaves.2.front.left.front.front.right")

    /// 􂴿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopRadiowaves2FrontLeftFrontFrontRightFill = SFSymbol(rawValue: "car.top.radiowaves.2.front.left.front.front.right.fill")

    /// 􂵂
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopRadiowaves2RearLeftRearRearRight = SFSymbol(rawValue: "car.top.radiowaves.2.rear.left.rear.rear.right")

    /// 􂵃
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopRadiowaves2RearLeftRearRearRightFill = SFSymbol(rawValue: "car.top.radiowaves.2.rear.left.rear.rear.right.fill")

    /// 􂵆
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let dotCarTopRadiowaves2RearLeftRearRearRight = SFSymbol(rawValue: "dot.car.top.radiowaves.2.rear.left.rear.rear.right")

    /// 􂵇
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let dotCarTopRadiowaves2RearLeftRearRearRightFill = SFSymbol(rawValue: "dot.car.top.radiowaves.2.rear.left.rear.rear.right.fill")

    /// 􀛫
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let envelopeStack = SFSymbol(rawValue: "envelope.stack")

    /// 􀛬
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let envelopeStackFill = SFSymbol(rawValue: "envelope.stack.fill")

    /// 􂷩
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Messages app.
    static let exclamationmarkMessage = SFSymbol(rawValue: "exclamationmark.message")

    /// 􂷪
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Messages app.
    static let exclamationmarkMessageFill = SFSymbol(rawValue: "exclamationmark.message.fill")

    /// 􂶩
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let handThumbsdownSlash = SFSymbol(rawValue: "hand.thumbsdown.slash")

    /// 􂶪
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let handThumbsdownSlashFill = SFSymbol(rawValue: "hand.thumbsdown.slash.fill")

    /// 􂶥
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let handThumbsupSlash = SFSymbol(rawValue: "hand.thumbsup.slash")

    /// 􂶦
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let handThumbsupSlashFill = SFSymbol(rawValue: "hand.thumbsup.slash.fill")

    /// 􂶟
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let laurelLeadingLaurelTrailing = SFSymbol(rawValue: "laurel.leading.laurel.trailing")

    /// 􂷃
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let memoriesBadgeCheckmark = SFSymbol(rawValue: "memories.badge.checkmark")

    /// 􂷁
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let memoriesBadgeXmark = SFSymbol(rawValue: "memories.badge.xmark")

    /// 􂷐
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let photoBadgeMagnifyingglass = SFSymbol(rawValue: "photo.badge.magnifyingglass")

    /// 􂷑
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let photoBadgeMagnifyingglassFill = SFSymbol(rawValue: "photo.badge.magnifyingglass.fill")

    /// 􂷫
    /// 2 Localizations, 2 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic (iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Messages app.
    static let questionmarkMessage = SymbolWith1Localization<Ar_v6_2>(rawValue: "questionmark.message")

    /// 􂷬
    /// 2 Localizations, 3 Layersets, ⚠️ Restricted
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic (iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Messages app.
    static let questionmarkMessageFill = SymbolWith1Localization<Ar_v6_2>(rawValue: "questionmark.message.fill")

    /// 􂶯
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let rectangleGrid3x1 = SFSymbol(rawValue: "rectangle.grid.3x1")

    /// 􂶰
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let rectangleGrid3x1Fill = SFSymbol(rawValue: "rectangle.grid.3x1.fill")

    /// 􂷡
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let squareAndArrowDownBadgeCheckmark = SFSymbol(rawValue: "square.and.arrow.down.badge.checkmark")

    /// 􂷢
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let squareAndArrowDownBadgeCheckmarkFill = SFSymbol(rawValue: "square.and.arrow.down.badge.checkmark.fill")

    /// 􂷥
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let squareAndArrowDownBadgeXmark = SFSymbol(rawValue: "square.and.arrow.down.badge.xmark")

    /// 􂷦
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let squareAndArrowDownBadgeXmarkFill = SFSymbol(rawValue: "square.and.arrow.down.badge.xmark.fill")

    /// 􂷝
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let waveformBadgeCheckmark = SFSymbol(rawValue: "waveform.badge.checkmark")

    /// 􂷞
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let waveformBadgeXmark = SFSymbol(rawValue: "waveform.badge.xmark")

    /// 􂵊
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let waveformPathEcgMagnifyingglass = SFSymbol(rawValue: "waveform.path.ecg.magnifyingglass")

    /// 􂷚
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static let waveformPathEcgText = SymbolWith1Localization<Rtl>(rawValue: "waveform.path.ecg.text")

    /// 􂵋
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let waveformPathEcgTextClipboard = SymbolWith1Localization<Rtl>(rawValue: "waveform.path.ecg.text.clipboard")

    /// 􂵌
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let waveformPathEcgTextClipboardFill = SymbolWith1Localization<Rtl>(rawValue: "waveform.path.ecg.text.clipboard.fill")

    /// 􀳼
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor
    static let waveformPathEcgTextPage = SymbolWith1Localization<Rtl>(rawValue: "waveform.path.ecg.text.page")

    /// 􀳽
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static let waveformPathEcgTextPageFill = SymbolWith1Localization<Rtl>(rawValue: "waveform.path.ecg.text.page.fill")
}
