// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 5.1 Symbols
@available(iOS 17.1, macOS 14.1, tvOS 17.1, watchOS 10.1, visionOS 1.0, *)
public extension SFSymbol {
    /// 􂉏
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let chevronCompactBackward = SFSymbol(rawValue: "chevron.compact.backward")

    /// 􂉐
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let chevronCompactForward = SFSymbol(rawValue: "chevron.compact.forward")

    /// 􂉚
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let personCropSquareBadgeCamera = SFSymbol(rawValue: "person.crop.square.badge.camera")

    /// 􂉛
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let personCropSquareBadgeCameraFill = SFSymbol(rawValue: "person.crop.square.badge.camera.fill")

    /// 􂉜
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let personCropSquareBadgeVideo = SFSymbol(rawValue: "person.crop.square.badge.video")

    /// 􂉝
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let personCropSquareBadgeVideoFill = SFSymbol(rawValue: "person.crop.square.badge.video.fill")
}
