// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 5.2 Symbols
@available(iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2, visionOS 1.1, *)
public extension SFSymbol {
    /// 􂋍
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let squareAndArrowUpBadgeClock = SFSymbol(rawValue: "square.and.arrow.up.badge.clock")

    /// 􂋏
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let squareAndArrowUpBadgeClockFill = SFSymbol(rawValue: "square.and.arrow.up.badge.clock.fill")
}
