// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 1.1 Symbols
@available(iOS 13.1, macOS 11.0, tvOS 13.0, watchOS 6.1, visionOS 1.0, *)
public extension SFSymbol {
    /// 􀞸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var arrowUturnLeftCircleBadgeEllipsis: SFSymbol { .init(rawValue: "arrow.uturn.left.circle.badge.ellipsis") }

    /// 􀞖
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var aspectratio: SFSymbol { .init(rawValue: "aspectratio") }

    /// 􀞏
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var aspectratioFill: SFSymbol { .init(rawValue: "aspectratio.fill") }

    /// 􀙘
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var car: SFSymbol { .init(rawValue: "car") }

    /// 􀞾
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var circleGrid2x2: SFSymbol { .init(rawValue: "circle.grid.2x2") }

    /// 􀞿
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var circleGrid2x2Fill: SFSymbol { .init(rawValue: "circle.grid.2x2.fill") }

    /// 􀝌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var flashlightOffFill: SFSymbol { .init(rawValue: "flashlight.off.fill") }

    /// 􀞋
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var flashlightOnFill: SFSymbol { .init(rawValue: "flashlight.on.fill") }

    /// 􀞒
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 13.1, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    @available(macOS, introduced: 11.0, deprecated: 11.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    @available(tvOS, introduced: 13.0, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    @available(watchOS, introduced: 6.1, deprecated: 7.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    static var flipHorizontal: SFSymbol { .init(rawValue: "flip.horizontal") }

    /// 􀞓
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 13.1, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    @available(macOS, introduced: 11.0, deprecated: 11.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    @available(tvOS, introduced: 13.0, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    @available(watchOS, introduced: 6.1, deprecated: 7.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    static var flipHorizontalFill: SFSymbol { .init(rawValue: "flip.horizontal.fill") }

    /// 􀜇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var mappinCircle: SFSymbol { .init(rawValue: "mappin.circle") }

    /// 􀜈
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor (iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0)
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var mappinCircleFill: SFSymbol { .init(rawValue: "mappin.circle.fill") }

    /// 􀒔
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var paperclipCircle: SFSymbol { .init(rawValue: "paperclip.circle") }

    /// 􀒕
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var paperclipCircleFill: SFSymbol { .init(rawValue: "paperclip.circle.fill") }

    /// 􀒴
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var pinCircle: SFSymbol { .init(rawValue: "pin.circle") }

    /// 􀒵
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor (iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0)
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var pinCircleFill: SFSymbol { .init(rawValue: "pin.circle.fill") }

    /// 􀞷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var scissorsBadgeEllipsis: SFSymbol { .init(rawValue: "scissors.badge.ellipsis") }

    /// 􀑔
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var studentdesk: SFSymbol { .init(rawValue: "studentdesk") }
}
