// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.1, macOS 15.1, tvOS 18.1, watchOS 11.1, visionOS 2.1, *)
extension SFSymbol {
    internal static var localizationsAvailableSince6_1: [SFSymbol : Set<Localization>] {
        [
            boltHouse: [],
            boltHouseFill: [],
            cableConnectorVideo: [],
            carTopRadiowaves2FrontLeftFrontFrontRight: [],
            carTopRadiowaves2FrontLeftFrontFrontRightFill: [],
            carTopRadiowaves2RearLeftRearRearRight: [],
            carTopRadiowaves2RearLeftRearRearRightFill: [],
            characterCircle: [.bn, .gu, .kn, .ml, .mni, .mr, .or, .pa, .sat, .si, .ta, .te],
            characterCircleFill: [.bn, .gu, .kn, .ml, .mni, .mr, .or, .pa, .sat, .si, .ta, .te],
            characterSquare: [.bn, .gu, .kn, .ml, .mni, .mr, .or, .pa, .sat, .si, .ta, .te],
            characterSquareFill: [.bn, .gu, .kn, .ml, .mni, .mr, .or, .pa, .sat, .si, .ta, .te],
            dotCarTopRadiowaves2RearLeftRearRearRight: [],
            dotCarTopRadiowaves2RearLeftRearRearRightFill: [],
            envelopeStack: [],
            envelopeStackFill: [],
            exclamationmarkMessage: [],
            exclamationmarkMessageFill: [],
            handThumbsdownSlash: [],
            handThumbsdownSlashFill: [],
            handThumbsupSlash: [],
            handThumbsupSlashFill: [],
            laurelLeadingLaurelTrailing: [],
            memoriesBadgeCheckmark: [],
            memoriesBadgeXmark: [],
            photoBadgeMagnifyingglass: [],
            photoBadgeMagnifyingglassFill: [],
            questionmarkMessage: [],
            questionmarkMessageFill: [],
            rectangleGrid3x1: [],
            rectangleGrid3x1Fill: [],
            squareAndArrowDownBadgeCheckmark: [],
            squareAndArrowDownBadgeCheckmarkFill: [],
            squareAndArrowDownBadgeXmark: [],
            squareAndArrowDownBadgeXmarkFill: [],
            waveformBadgeCheckmark: [],
            waveformBadgeXmark: [],
            waveformPathEcgMagnifyingglass: [],
            waveformPathEcgText: [.rtl],
            waveformPathEcgTextClipboard: [.rtl],
            waveformPathEcgTextClipboardFill: [.rtl],
            waveformPathEcgTextPage: [.rtl],
            waveformPathEcgTextPageFill: [.rtl]
        ]
    }

    internal static var symbolsDeprecatedSince6_1: Set<SFSymbol> {
        [
            ecgTextPage,
            ecgTextPageFill
        ]
    }
}
