// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *)
extension SFSymbol {
    internal static var localizationsAvailableSince6_2: [SFSymbol : Set<Localization>] {
        [
            airpodsGen4: [],
            airpodsGen4ChargingcaseWireless: [],
            airpodsGen4ChargingcaseWirelessFill: [],
            airpodsGen4Left: [],
            airpodsGen4Right: [],
            appleWritingTools: [],
            exclamationmarkTriangleTextPage: [.rtl],
            exclamationmarkTriangleTextPageFill: [.rtl],
            figureSeatedSideLeftAirDistributionUpperAndMiddleAndLower: [],
            figureSeatedSideRightAirDistributionUpperAndMiddleAndLower: [],
            headphonesDots: [],
            infoTriangle: [],
            infoTriangleFill: [],
            insetFilledRectangleAndPersonFilledCircle: [],
            insetFilledRectangleAndPersonFilledCircleFill: [],
            questionmarkMessage: [.ar],
            questionmarkMessageFill: [.ar],
            receipt: [],
            receiptFill: [],
            wandAndOutline: [],
            wandAndOutlineInverse: []
        ]
    }

    internal static var symbolsDeprecatedSince6_2: Set<SFSymbol> {
        []
    }
}
