// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 3.2 Symbols
@available(iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3, visionOS 1.0, *)
public extension SFSymbol {
    /// 􁄣
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodGen3Left = SFSymbol(rawValue: "airpod.gen3.left")

    /// 􁄢
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodGen3Right = SFSymbol(rawValue: "airpod.gen3.right")

    /// 􁄡
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen3 = SFSymbol(rawValue: "airpods.gen3")

    /// 􁅐
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen3ChargingcaseWireless = SFSymbol(rawValue: "airpods.gen3.chargingcase.wireless")

    /// 􁅑
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static let airpodsGen3ChargingcaseWirelessFill = SFSymbol(rawValue: "airpods.gen3.chargingcase.wireless.fill")

    /// 􁅞
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Fit Pro.
    @available(iOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitpro")
    @available(macOS, introduced: 12.1, deprecated: 14.0, renamed: "beatsFitpro")
    @available(tvOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitpro")
    @available(watchOS, introduced: 8.3, deprecated: 10.0, renamed: "beatsFitpro")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "beatsFitpro")
    static let beatsFitPro = SFSymbol(rawValue: "beats.fit.pro")

    /// 􁅡
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Fit Pro case.
    @available(iOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproChargingcase")
    @available(macOS, introduced: 12.1, deprecated: 14.0, renamed: "beatsFitproChargingcase")
    @available(tvOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproChargingcase")
    @available(watchOS, introduced: 8.3, deprecated: 10.0, renamed: "beatsFitproChargingcase")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "beatsFitproChargingcase")
    static let beatsFitProChargingcase = SFSymbol(rawValue: "beats.fit.pro.chargingcase")

    /// 􁅢
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Fit Pro case.
    @available(iOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproChargingcaseFill")
    @available(macOS, introduced: 12.1, deprecated: 14.0, renamed: "beatsFitproChargingcaseFill")
    @available(tvOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproChargingcaseFill")
    @available(watchOS, introduced: 8.3, deprecated: 10.0, renamed: "beatsFitproChargingcaseFill")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "beatsFitproChargingcaseFill")
    static let beatsFitProChargingcaseFill = SFSymbol(rawValue: "beats.fit.pro.chargingcase.fill")

    /// 􁅟
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Fit Pro.
    @available(iOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproLeft")
    @available(macOS, introduced: 12.1, deprecated: 14.0, renamed: "beatsFitproLeft")
    @available(tvOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproLeft")
    @available(watchOS, introduced: 8.3, deprecated: 10.0, renamed: "beatsFitproLeft")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "beatsFitproLeft")
    static let beatsFitProLeft = SFSymbol(rawValue: "beats.fit.pro.left")

    /// 􁅠
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Beats Fit Pro.
    @available(iOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproRight")
    @available(macOS, introduced: 12.1, deprecated: 14.0, renamed: "beatsFitproRight")
    @available(tvOS, introduced: 15.2, deprecated: 17.0, renamed: "beatsFitproRight")
    @available(watchOS, introduced: 8.3, deprecated: 10.0, renamed: "beatsFitproRight")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "beatsFitproRight")
    static let beatsFitProRight = SFSymbol(rawValue: "beats.fit.pro.right")

    /// 􁋶
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let rectangleLeadinghalfFilled = SFSymbol(rawValue: "rectangle.leadinghalf.filled")

    /// 􁋷
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let rectangleTrailinghalfFilled = SFSymbol(rawValue: "rectangle.trailinghalf.filled")

    /// 􁋽
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let square3Layers3dDownLeftSlash = SFSymbol(rawValue: "square.3.layers.3d.down.left.slash")

    /// 􁋼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let square3Layers3dDownRightSlash = SFSymbol(rawValue: "square.3.layers.3d.down.right.slash")

    /// 􁌅
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    @available(iOS, introduced: 15.2, deprecated: 16.0, renamed: "square3Layers3dSlash")
    @available(macOS, introduced: 12.1, deprecated: 13.0, renamed: "square3Layers3dSlash")
    @available(tvOS, introduced: 15.2, deprecated: 16.0, renamed: "square3Layers3dSlash")
    @available(watchOS, introduced: 8.3, deprecated: 9.0, renamed: "square3Layers3dSlash")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "square3Layers3dSlash")
    static let square3Stack3dSlash = SFSymbol(rawValue: "square.3.stack.3d.slash")
}
