// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 6.2 Symbols
@available(iOS 18.2, macOS 15.2, tvOS 18.2, watchOS 11.2, visionOS 2.2, *)
public extension SFSymbol {
    /// 􂭃
    /// ![airpods.gen4](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/airpods.gen4.png)
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static var airpodsGen4: SFSymbol { .init(rawValue: "airpods.gen4") }

    /// 􂭆
    /// ![airpods.gen4.chargingcase.wireless](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/airpods.gen4.chargingcase.wireless.png)
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static var airpodsGen4ChargingcaseWireless: SFSymbol { .init(rawValue: "airpods.gen4.chargingcase.wireless") }

    /// 􂭇
    /// ![airpods.gen4.chargingcase.wireless.fill](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/airpods.gen4.chargingcase.wireless.fill.png)
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static var airpodsGen4ChargingcaseWirelessFill: SFSymbol { .init(rawValue: "airpods.gen4.chargingcase.wireless.fill") }

    /// 􂭅
    /// ![airpods.gen4.left](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/airpods.gen4.left.png)
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static var airpodsGen4Left: SFSymbol { .init(rawValue: "airpods.gen4.left") }

    /// 􂭄
    /// ![airpods.gen4.right](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/airpods.gen4.right.png)
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods.
    static var airpodsGen4Right: SFSymbol { .init(rawValue: "airpods.gen4.right") }

    /// 􂷴
    /// ![apple.writing.tools](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/apple.writing.tools.png)
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Writing Tools.
    static var appleWritingTools: SFSymbol { .init(rawValue: "apple.writing.tools") }

    /// 􂹞
    /// ![exclamationmark.triangle.text.page](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/exclamationmark.triangle.text.page.png)
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static var exclamationmarkTriangleTextPage: SymbolWith1Localization<Rtl> { .init(rawValue: "exclamationmark.triangle.text.page") }

    /// 􂹟
    /// ![exclamationmark.triangle.text.page.fill](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/exclamationmark.triangle.text.page.fill.png)
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static var exclamationmarkTriangleTextPageFill: SymbolWith1Localization<Rtl> { .init(rawValue: "exclamationmark.triangle.text.page.fill") }

    /// 􂸞
    /// ![figure.seated.side.left.air.distribution.upper.and.middle.and.lower](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/figure.seated.side.left.air.distribution.upper.and.middle.and.lower.png)
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var figureSeatedSideLeftAirDistributionUpperAndMiddleAndLower: SFSymbol { .init(rawValue: "figure.seated.side.left.air.distribution.upper.and.middle.and.lower") }

    /// 􂸟
    /// ![figure.seated.side.right.air.distribution.upper.and.middle.and.lower](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/figure.seated.side.right.air.distribution.upper.and.middle.and.lower.png)
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var figureSeatedSideRightAirDistributionUpperAndMiddleAndLower: SFSymbol { .init(rawValue: "figure.seated.side.right.air.distribution.upper.and.middle.and.lower") }

    /// 􂸔
    /// ![headphones.dots](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/headphones.dots.png)
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var headphonesDots: SFSymbol { .init(rawValue: "headphones.dots") }

    /// 􂹩
    /// ![info.triangle](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/info.triangle.png)
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var infoTriangle: SFSymbol { .init(rawValue: "info.triangle") }

    /// 􂹪
    /// ![info.triangle.fill](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/info.triangle.fill.png)
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static var infoTriangleFill: SFSymbol { .init(rawValue: "info.triangle.fill") }

    /// 􂸆
    /// ![inset.filled.rectangle.and.person.filled.circle](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/inset.filled.rectangle.and.person.filled.circle.png)
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var insetFilledRectangleAndPersonFilledCircle: SFSymbol { .init(rawValue: "inset.filled.rectangle.and.person.filled.circle") }

    /// 􂸇
    /// ![inset.filled.rectangle.and.person.filled.circle.fill](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/inset.filled.rectangle.and.person.filled.circle.fill.png)
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static var insetFilledRectangleAndPersonFilledCircleFill: SFSymbol { .init(rawValue: "inset.filled.rectangle.and.person.filled.circle.fill") }

    /// 􂷼
    /// ![receipt](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/receipt.png)
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var receipt: SFSymbol { .init(rawValue: "receipt") }

    /// 􂷽
    /// ![receipt.fill](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/receipt.fill.png)
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var receiptFill: SFSymbol { .init(rawValue: "receipt.fill") }

    /// 􂸊
    /// ![wand.and.outline](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/wand.and.outline.png)
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var wandAndOutline: SFSymbol { .init(rawValue: "wand.and.outline") }

    /// 􂸋
    /// ![wand.and.outline.inverse](https://raw.githubusercontent.com/SFSafeSymbols/SFSafeSymbols/refs/heads/stable/Sources/SFSafeSymbols/SymbolImages/wand.and.outline.inverse.png)
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static var wandAndOutlineInverse: SFSymbol { .init(rawValue: "wand.and.outline.inverse") }
}
