// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 6.3 Symbols
@available(iOS 18.4, macOS 15.4, tvOS 18.4, watchOS 11.4, visionOS 2.4, *)
public extension SFSymbol {
    /// 􁂋
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let arrowBackwardToLineCompact = SFSymbol(rawValue: "arrow.backward.to.line.compact")

    /// 􁂏
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let arrowForwardToLineCompact = SFSymbol(rawValue: "arrow.forward.to.line.compact")

    /// 􂹼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carSideArrowLeftAndRight = SFSymbol(rawValue: "car.side.arrow.left.and.right")

    /// 􂹽
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carSideArrowLeftAndRightFill = SFSymbol(rawValue: "car.side.arrow.left.and.right.fill")

    /// 􂼛
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let carSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle = SFSymbol(rawValue: "car.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle")

    /// 􂼜
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let carSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill = SFSymbol(rawValue: "car.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill")

    /// 􂻳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carSideRearAndCollisionAndCarSideFrontAndArrowForward = SFSymbol(rawValue: "car.side.rear.and.collision.and.car.side.front.and.arrow.forward")

    /// 􂼚
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carSideRearAndCollisionAndCarSideFrontAndSteeringwheel = SFSymbol(rawValue: "car.side.rear.and.collision.and.car.side.front.and.steeringwheel")

    /// 􂺯
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopLaneDashedDepartureLeftSlash = SFSymbol(rawValue: "car.top.lane.dashed.departure.left.slash")

    /// 􂺱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopLaneDashedDepartureLeftSlashFill = SFSymbol(rawValue: "car.top.lane.dashed.departure.left.slash.fill")

    /// 􂺳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopLaneDashedDepartureRightSlash = SFSymbol(rawValue: "car.top.lane.dashed.departure.right.slash")

    /// 􂺵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let carTopLaneDashedDepartureRightSlashFill = SFSymbol(rawValue: "car.top.lane.dashed.departure.right.slash.fill")

    /// 􂺹
    /// 19 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Bengali
    /// - Chinese
    /// - Gujarati
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Kannada
    /// - Korean
    /// - Malayalam
    /// - Manipuri
    /// - Maranthi
    /// - Oriya
    /// - Punjabi
    /// - Santali
    /// - Sinhala
    /// - Tamil
    /// - Thai
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let characterTextboxBadgeSparkles = SymbolWith18Localizations<Ar, Bn, Gu, He, Hi, Ja, Kn, Ko, Ml, Mni, Mr, Or, Pa, Sat, Si, Ta, Th, Zh>(rawValue: "character.textbox.badge.sparkles")

    /// 􂺀
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let convertibleSideArrowLeftAndRight = SFSymbol(rawValue: "convertible.side.arrow.left.and.right")

    /// 􂺁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let convertibleSideArrowLeftAndRightFill = SFSymbol(rawValue: "convertible.side.arrow.left.and.right.fill")

    /// 􂼧
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let convertibleSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle = SFSymbol(rawValue: "convertible.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle")

    /// 􂼨
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let convertibleSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill = SFSymbol(rawValue: "convertible.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill")

    /// 􀫌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 18.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(macOS, introduced: 15.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(tvOS, introduced: 18.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(watchOS, introduced: 11.4, deprecated: 26.0, renamed: "pointerArrow")
    @available(visionOS, introduced: 2.4, deprecated: 26.0, renamed: "pointerArrow")
    static let cursorarrowResizeNorthEastSouthEast = SFSymbol(rawValue: "cursorarrow.resize.north.east.south.east")

    /// 􂼙
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let electronicTollCollection = SFSymbol(rawValue: "electronic.toll.collection")

    /// 􂺟
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let electronicTollCollectionRectangle = SFSymbol(rawValue: "electronic.toll.collection.rectangle")

    /// 􂺦
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let electronicTollCollectionRectangleFill = SFSymbol(rawValue: "electronic.toll.collection.rectangle.fill")

    /// 􂺠
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let electronicTollCollectionRectangleSlash = SFSymbol(rawValue: "electronic.toll.collection.rectangle.slash")

    /// 􂺧
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let electronicTollCollectionRectangleSlashFill = SFSymbol(rawValue: "electronic.toll.collection.rectangle.slash.fill")

    /// 􂺢
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let electronicTollCollectionRectangleTrianglebadgeExclamationmark = SFSymbol(rawValue: "electronic.toll.collection.rectangle.trianglebadge.exclamationmark")

    /// 􂺩
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let electronicTollCollectionRectangleTrianglebadgeExclamationmarkFill = SFSymbol(rawValue: "electronic.toll.collection.rectangle.trianglebadge.exclamationmark.fill")

    /// 􂼵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let engineEmissionAndDrop2WaterWaveBelow = SFSymbol(rawValue: "engine.emission.and.drop.2.water.wave.below")

    /// 􂻴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let envelopeAndArrow3Down = SFSymbol(rawValue: "envelope.and.arrow.3.down")

    /// 􂻵
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let envelopeAndArrow3DownFill = SFSymbol(rawValue: "envelope.and.arrow.3.down.fill")

    /// 􂼊
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let flagPatternCheckeredLc = SFSymbol(rawValue: "flag.pattern.checkered.lc")

    /// 􂼋
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let fuelFilterWater = SFSymbol(rawValue: "fuel.filter.water")

    /// 􂼅
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let hydrogen = SFSymbol(rawValue: "hydrogen")

    /// 􂼆
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let hydrogenCircle = SFSymbol(rawValue: "hydrogen.circle")

    /// 􂼇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let hydrogenCircleFill = SFSymbol(rawValue: "hydrogen.circle.fill")

    /// 􂼈
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let hydrogenSquare = SFSymbol(rawValue: "hydrogen.square")

    /// 􂼉
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let hydrogenSquareFill = SFSymbol(rawValue: "hydrogen.square.fill")

    /// 􂹚
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static let infoCircleTextPage = SymbolWith1Localization<Rtl>(rawValue: "info.circle.text.page")

    /// 􂹛
    /// 2 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    static let infoCircleTextPageFill = SymbolWith1Localization<Rtl>(rawValue: "info.circle.text.page.fill")

    /// 􂻶
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keyCarSide = SFSymbol(rawValue: "key.car.side")

    /// 􂻷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let keyCarSideFill = SFSymbol(rawValue: "key.car.side.fill")

    /// 􂻺
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keyConvertibleSide = SFSymbol(rawValue: "key.convertible.side")

    /// 􂻻
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let keyConvertibleSideFill = SFSymbol(rawValue: "key.convertible.side.fill")

    /// 􂻸
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keySuvSide = SFSymbol(rawValue: "key.suv.side")

    /// 􂻹
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let keySuvSideFill = SFSymbol(rawValue: "key.suv.side.fill")

    /// 􂻼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keyTruckPickupSide = SFSymbol(rawValue: "key.truck.pickup.side")

    /// 􂻽
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let keyTruckPickupSideFill = SFSymbol(rawValue: "key.truck.pickup.side.fill")

    /// 􂽱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let longTextPageAndPencil = SFSymbol(rawValue: "long.text.page.and.pencil")

    /// 􂽴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let longTextPageAndPencilFill = SFSymbol(rawValue: "long.text.page.and.pencil.fill")

    /// 􂶷
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static let macminiGen2 = SFSymbol(rawValue: "macmini.gen2")

    /// 􂶸
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static let macminiGen2Fill = SFSymbol(rawValue: "macmini.gen2.fill")

    /// 􂶹
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static let macminiGen3 = SFSymbol(rawValue: "macmini.gen3")

    /// 􂶺
    /// Single Localization, Single Layerset, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s Mac mini.
    static let macminiGen3Fill = SFSymbol(rawValue: "macmini.gen3.fill")

    /// 􂺂
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let memoriesSlash = SFSymbol(rawValue: "memories.slash")

    /// 􂹸
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let minusPlusBatteryblockStackArrowtriangleLeft = SFSymbol(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.left")

    /// 􂹺
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let minusPlusBatteryblockStackArrowtriangleLeftFill = SFSymbol(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.left.fill")

    /// 􂹴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let minusPlusBatteryblockStackArrowtriangleRight = SFSymbol(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right")

    /// 􂼕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let minusPlusBatteryblockStackArrowtriangleRightAndArrowtriangleLeft = SFSymbol(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right.and.arrowtriangle.left")

    /// 􂼖
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let minusPlusBatteryblockStackArrowtriangleRightAndArrowtriangleLeftFill = SFSymbol(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right.and.arrowtriangle.left.fill")

    /// 􂹶
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let minusPlusBatteryblockStackArrowtriangleRightFill = SFSymbol(rawValue: "minus.plus.batteryblock.stack.arrowtriangle.right.fill")

    /// 􂼫
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let nosignBadgeClock = SFSymbol(rawValue: "nosign.badge.clock")

    /// 􂻫
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let personCheckmarkAndXmark = SymbolWith1Localization<Rtl>(rawValue: "person.checkmark.and.xmark")

    /// 􂻬
    /// 2 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Left-to-Right
    /// - Right-to-Left
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let personFillCheckmarkAndXmark = SymbolWith1Localization<Rtl>(rawValue: "person.fill.checkmark.and.xmark")

    /// 􂼭
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let photoBadgeShieldExclamationmark = SFSymbol(rawValue: "photo.badge.shield.exclamationmark")

    /// 􂼷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let photoBadgeShieldExclamationmarkFill = SFSymbol(rawValue: "photo.badge.shield.exclamationmark.fill")

    /// 􂼯
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let photoTrianglebadgeExclamationmark = SFSymbol(rawValue: "photo.trianglebadge.exclamationmark")

    /// 􂼸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let photoTrianglebadgeExclamationmarkFill = SFSymbol(rawValue: "photo.trianglebadge.exclamationmark.fill")

    /// 􂹯
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let pi = SFSymbol(rawValue: "pi")

    /// 􂹰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let piCircle = SFSymbol(rawValue: "pi.circle")

    /// 􂹱
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let piCircleFill = SFSymbol(rawValue: "pi.circle.fill")

    /// 􂹲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let piSquare = SFSymbol(rawValue: "pi.square")

    /// 􂹳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let piSquareFill = SFSymbol(rawValue: "pi.square.fill")

    /// 􂻥
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let plusMinusCapsule = SFSymbol(rawValue: "plus.minus.capsule")

    /// 􂻦
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let plusMinusCapsuleFill = SFSymbol(rawValue: "plus.minus.capsule.fill")

    /// 􂻛
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    @available(iOS, introduced: 18.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(macOS, introduced: 15.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(tvOS, introduced: 18.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(watchOS, introduced: 11.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    @available(visionOS, introduced: 2.4, deprecated: 26.0, renamed: "repeatBadgeXmark")
    static let repeatBadgeXmarkCircleFill = SFSymbol(rawValue: "repeat.badge.xmark.circle.fill")

    /// 􂼀
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let roadLaneArrowtriangle2Outward = SFSymbol(rawValue: "road.lane.arrowtriangle.2.outward")

    /// 􂼳
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let roboticVacuumAndArrowtriangleUp = SFSymbol(rawValue: "robotic.vacuum.and.arrowtriangle.up")

    /// 􂼴
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let roboticVacuumAndArrowtriangleUpFill = SFSymbol(rawValue: "robotic.vacuum.and.arrowtriangle.up.fill")

    /// 􂼱
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    static let roboticVacuumAndEllipsis = SFSymbol(rawValue: "robotic.vacuum.and.ellipsis")

    /// 􂼲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    static let roboticVacuumAndEllipsisFill = SFSymbol(rawValue: "robotic.vacuum.and.ellipsis.fill")

    /// 􂻝
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let spoonServing = SFSymbol(rawValue: "spoon.serving")

    /// 􂼽
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let squareAndArrowUpBadgeCheckmark = SFSymbol(rawValue: "square.and.arrow.up.badge.checkmark")

    /// 􂼾
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor
    static let squareAndArrowUpBadgeCheckmarkFill = SFSymbol(rawValue: "square.and.arrow.up.badge.checkmark.fill")

    /// 􀮌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let squareshapeSplit2x2DottedInside = SFSymbol(rawValue: "squareshape.split.2x2.dotted.inside")

    /// 􁓓
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let squareshapeSplit2x2DottedInsideAndOutside = SFSymbol(rawValue: "squareshape.split.2x2.dotted.inside.and.outside")

    /// 􂼼
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let squareshapeSplit2x2DottedOutside = SFSymbol(rawValue: "squareshape.split.2x2.dotted.outside")

    /// 􂺷
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let starHexagon = SFSymbol(rawValue: "star.hexagon")

    /// 􂺸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    /// - Multicolor (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let starHexagonFill = SFSymbol(rawValue: "star.hexagon.fill")

    /// 􂹾
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suvSideArrowLeftAndRight = SFSymbol(rawValue: "suv.side.arrow.left.and.right")

    /// 􂹿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let suvSideArrowLeftAndRightFill = SFSymbol(rawValue: "suv.side.arrow.left.and.right.fill")

    /// 􂼟
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let suvSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle = SFSymbol(rawValue: "suv.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle")

    /// 􂼠
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let suvSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill = SFSymbol(rawValue: "suv.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill")

    /// 􂺫
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let truckPickupSideArrowLeftAndRight = SFSymbol(rawValue: "truck.pickup.side.arrow.left.and.right")

    /// 􂺬
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let truckPickupSideArrowLeftAndRightFill = SFSymbol(rawValue: "truck.pickup.side.arrow.left.and.right.fill")

    /// 􂼣
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let truckPickupSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangle = SFSymbol(rawValue: "truck.pickup.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle")

    /// 􂼤
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 18.5, macOS 15.5, tvOS 18.5, watchOS 11.5)
    static let truckPickupSideHillDownAndGaugeOpenWithLinesNeedle25percentAndArrowtriangleFill = SFSymbol(rawValue: "truck.pickup.side.hill.down.and.gauge.open.with.lines.needle.25percent.and.arrowtriangle.fill")
}
