// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 2.1 Symbols
@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
public extension SFSymbol {
    /// 􀵀
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let aqiHigh = NonLocalizedSymbol(rawValue: "aqi.high")

    /// 􀴾
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let aqiLow = NonLocalizedSymbol(rawValue: "aqi.low")

    /// 􀴿
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let aqiMedium = NonLocalizedSymbol(rawValue: "aqi.medium")

    /// 􀮰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let brazilianrealsignCircle = NonLocalizedSymbol(rawValue: "brazilianrealsign.circle")

    /// 􀮱
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let brazilianrealsignCircleFill = NonLocalizedSymbol(rawValue: "brazilianrealsign.circle.fill")

    /// 􀮲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let brazilianrealsignSquare = NonLocalizedSymbol(rawValue: "brazilianrealsign.square")

    /// 􀮳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let brazilianrealsignSquareFill = NonLocalizedSymbol(rawValue: "brazilianrealsign.square.fill")

    /// 􀒭
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let cartCircle = NonLocalizedSymbol(rawValue: "cart.circle")

    /// 􀒮
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let cartCircleFill = NonLocalizedSymbol(rawValue: "cart.circle.fill")

    /// 􀅏
    /// 9 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Traditional Chinese
    ///
    /// Layersets:
    /// - Monochrome
    static let character = SymbolWith8Localizations<Ar, He, Hi, Ja, Ko, Th, Zh, ZhTraditional>(rawValue: "character")

    /// 􀫕
    /// 9 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Traditional Chinese
    ///
    /// Layersets:
    /// - Monochrome
    static let characterBookClosed = SymbolWith8Localizations<Ar, He, Hi, Ja, Ko, Th, Zh, ZhTraditional>(rawValue: "character.book.closed")

    /// 􀫖
    /// 9 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Traditional Chinese
    ///
    /// Layersets:
    /// - Monochrome
    static let characterBookClosedFill = SymbolWith8Localizations<Ar, He, Hi, Ja, Ko, Th, Zh, ZhTraditional>(rawValue: "character.book.closed.fill")

    /// 􀯛
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let clockArrow2Circlepath = NonLocalizedSymbol(rawValue: "clock.arrow.2.circlepath")

    /// 􀯝
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let directcurrent = NonLocalizedSymbol(rawValue: "directcurrent")

    /// 􀵄
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Watch.
    static let exclamationmarkApplewatch = NonLocalizedSymbol(rawValue: "exclamationmark.applewatch")

    /// 􀵏
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let infinityCircle = NonLocalizedSymbol(rawValue: "infinity.circle")

    /// 􀵐
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let infinityCircleFill = NonLocalizedSymbol(rawValue: "infinity.circle.fill")

    /// 􀴓
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadBadgePlay = NonLocalizedSymbol(rawValue: "ipad.badge.play")

    /// 􀴒
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadHomebuttonBadgePlay = NonLocalizedSymbol(rawValue: "ipad.homebutton.badge.play")

    /// 􀵑
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadHomebuttonLandscapeBadgePlay = NonLocalizedSymbol(rawValue: "ipad.homebutton.landscape.badge.play")

    /// 􀵒
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static let ipadLandscapeBadgePlay = NonLocalizedSymbol(rawValue: "ipad.landscape.badge.play")

    /// 􀴑
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneBadgePlay = NonLocalizedSymbol(rawValue: "iphone.badge.play")

    /// 􀐶
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneHomebuttonBadgePlay = NonLocalizedSymbol(rawValue: "iphone.homebutton.badge.play")

    /// 􀴎
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneHomebuttonLandscape = NonLocalizedSymbol(rawValue: "iphone.homebutton.landscape")

    /// 􀴏
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static let iphoneLandscape = NonLocalizedSymbol(rawValue: "iphone.landscape")

    /// 􀴐
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPod touch.
    static let ipodtouchLandscape = NonLocalizedSymbol(rawValue: "ipodtouch.landscape")

    /// 􀵅
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Watch.
    static let lockApplewatch = NonLocalizedSymbol(rawValue: "lock.applewatch")

    /// 􀵪
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let photoTv = NonLocalizedSymbol(rawValue: "photo.tv")

    /// 􀵨
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let playTv = NonLocalizedSymbol(rawValue: "play.tv")

    /// 􀵩
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let playTvFill = NonLocalizedSymbol(rawValue: "play.tv.fill")

    /// 􀵚
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let rectangleBadgePersonCrop = NonLocalizedSymbol(rawValue: "rectangle.badge.person.crop")

    /// 􀵛
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let rectangleFillBadgePersonCrop = NonLocalizedSymbol(rawValue: "rectangle.fill.badge.person.crop")

    /// 􀴊
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 14.2, deprecated: 14.5, renamed: "rectangleTopthirdInsetFill")
    @available(macOS, introduced: 11.0, deprecated: 11.3, renamed: "rectangleTopthirdInsetFill")
    @available(tvOS, introduced: 14.2, deprecated: 14.5, renamed: "rectangleTopthirdInsetFill")
    @available(watchOS, introduced: 7.1, deprecated: 7.4, renamed: "rectangleTopthirdInsetFill")
    static let rectangleTopthirdInset = NonLocalizedSymbol(rawValue: "rectangle.topthird.inset")

    /// 􀵍
    /// 3 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Hindi (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let repeat1Circle = SymbolWith2Localizations<Ar_v3, Hi_v3>(rawValue: "repeat.1.circle")

    /// 􀵎
    /// 3 Localizations, 3 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Hindi (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let repeat1CircleFill = SymbolWith2Localizations<Ar_v3, Hi_v3>(rawValue: "repeat.1.circle.fill")

    /// 􀵋
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let repeatCircle = NonLocalizedSymbol(rawValue: "repeat.circle")

    /// 􀵌
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let repeatCircleFill = NonLocalizedSymbol(rawValue: "repeat.circle.fill")

    /// 􀵔
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 14.2, deprecated: 15.0, renamed: "checkerboardShield")
    @available(macOS, introduced: 11.0, deprecated: 12.0, renamed: "checkerboardShield")
    @available(tvOS, introduced: 14.2, deprecated: 15.0, renamed: "checkerboardShield")
    @available(watchOS, introduced: 7.1, deprecated: 8.0, renamed: "checkerboardShield")
    static let shieldCheckerboard = NonLocalizedSymbol(rawValue: "shield.checkerboard")

    /// 􀵉
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let shuffleCircle = NonLocalizedSymbol(rawValue: "shuffle.circle")

    /// 􀵊
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let shuffleCircleFill = NonLocalizedSymbol(rawValue: "shuffle.circle.fill")

    /// 􀵿
    /// 9 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Traditional Chinese
    ///
    /// Layersets:
    /// - Monochrome
    static let textformatSizeLarger = SymbolWith8Localizations<Ar, He, Hi, Ja, Ko, Th, Zh, ZhTraditional>(rawValue: "textformat.size.larger")

    /// 􀵷
    /// 9 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Traditional Chinese
    ///
    /// Layersets:
    /// - Monochrome
    static let textformatSizeSmaller = SymbolWith8Localizations<Ar, He, Hi, Ja, Ko, Th, Zh, ZhTraditional>(rawValue: "textformat.size.smaller")

    /// 􀴌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let torus = NonLocalizedSymbol(rawValue: "torus")

    /// 􀲰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let tvAndMediabox = NonLocalizedSymbol(rawValue: "tv.and.mediabox")
}
