// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5, *)
extension SFSymbol {
    internal static var symbolsAvailableSince3_3: Set<SFSymbol> {
        [
            cameraMacro,
            cameraMacroCircle,
            cameraMacroCircleFill,
            dotsAndLineVerticalAndCursorarrowRectangle,
            keyViewfinder,
            personBadgeKey,
            personBadgeKeyFill
        ]
    }

    internal static var symbolsDeprecatedSince3_3: Set<SFSymbol> {
        []
    }
}
