// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 2.1 Symbols
@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
public extension SFSymbol {
    /// 􀵀
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var aqiHigh: SFSymbol { .init(rawValue: "aqi.high") }

    /// 􀴾
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var aqiLow: SFSymbol { .init(rawValue: "aqi.low") }

    /// 􀴿
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var aqiMedium: SFSymbol { .init(rawValue: "aqi.medium") }

    /// 􀮰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var brazilianrealsignCircle: SFSymbol { .init(rawValue: "brazilianrealsign.circle") }

    /// 􀮱
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var brazilianrealsignCircleFill: SFSymbol { .init(rawValue: "brazilianrealsign.circle.fill") }

    /// 􀮲
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var brazilianrealsignSquare: SFSymbol { .init(rawValue: "brazilianrealsign.square") }

    /// 􀮳
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var brazilianrealsignSquareFill: SFSymbol { .init(rawValue: "brazilianrealsign.square.fill") }

    /// 􀒭
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var cartCircle: SFSymbol { .init(rawValue: "cart.circle") }

    /// 􀒮
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var cartCircleFill: SFSymbol { .init(rawValue: "cart.circle.fill") }

    /// 􀅏
    /// 20 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Bengali (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Gujarati (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Kannada (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Malayalam (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Manipuri (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Maranthi (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Oriya (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Punjabi (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Santali (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Sinhala (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Tamil (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Telugu (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    ///
    /// Layersets:
    /// - Monochrome
    static var character: SymbolWith19Localizations<Ar, Bn_v6, Gu_v6, He, Hi, Ja, Kn_v6, Ko, Ml_v6, Mni_v6, Mr_v6, Or_v6, Pa_v6, Sat_v6, Si_v6, Ta_v6, Te_v6, Th, Zh> { .init(rawValue: "character") }

    /// 􀫕
    /// 20 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Bengali (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Gujarati (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Kannada (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Malayalam (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Manipuri (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Maranthi (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Oriya (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Punjabi (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Santali (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Sinhala (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Tamil (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Telugu (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    ///
    /// Layersets:
    /// - Monochrome
    static var characterBookClosed: SymbolWith19Localizations<Ar, Bn_v7, Gu_v7, He, Hi, Ja, Kn_v7, Ko, Ml_v7, Mni_v7, Mr_v7, Or_v7, Pa_v7, Sat_v7, Si_v7, Ta_v7, Te_v7, Th, Zh> { .init(rawValue: "character.book.closed") }

    /// 􀫖
    /// 20 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Bengali (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Gujarati (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Kannada (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Malayalam (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Manipuri (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Maranthi (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Oriya (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Punjabi (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Santali (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Sinhala (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Tamil (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    /// - Telugu (iOS 26.0, macOS 26.0, tvOS 26.0, watchOS 26.0)
    ///
    /// Layersets:
    /// - Monochrome
    static var characterBookClosedFill: SymbolWith19Localizations<Ar, Bn_v7, Gu_v7, He, Hi, Ja, Kn_v7, Ko, Ml_v7, Mni_v7, Mr_v7, Or_v7, Pa_v7, Sat_v7, Si_v7, Ta_v7, Te_v7, Th, Zh> { .init(rawValue: "character.book.closed.fill") }

    /// 􀯛
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    @available(iOS, introduced: 14.2, deprecated: 18.0, renamed: "clockArrowTrianglehead2CounterclockwiseRotate90")
    @available(macOS, introduced: 11.0, deprecated: 15.0, renamed: "clockArrowTrianglehead2CounterclockwiseRotate90")
    @available(tvOS, introduced: 14.2, deprecated: 18.0, renamed: "clockArrowTrianglehead2CounterclockwiseRotate90")
    @available(watchOS, introduced: 7.1, deprecated: 11.0, renamed: "clockArrowTrianglehead2CounterclockwiseRotate90")
    @available(visionOS, introduced: 1.0, deprecated: 2.0, renamed: "clockArrowTrianglehead2CounterclockwiseRotate90")
    static var clockArrow2Circlepath: SFSymbol { .init(rawValue: "clock.arrow.2.circlepath") }

    /// 􀯝
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var directcurrent: SFSymbol { .init(rawValue: "directcurrent") }

    /// 􀵄
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Watch.
    static var exclamationmarkApplewatch: SFSymbol { .init(rawValue: "exclamationmark.applewatch") }

    /// 􀵏
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var infinityCircle: SFSymbol { .init(rawValue: "infinity.circle") }

    /// 􀵐
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var infinityCircleFill: SFSymbol { .init(rawValue: "infinity.circle.fill") }

    /// 􀴓
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static var ipadBadgePlay: SFSymbol { .init(rawValue: "ipad.badge.play") }

    /// 􀴒
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    @available(iOS, introduced: 14.2, deprecated: 16.1, renamed: "ipadGen1BadgePlay")
    @available(macOS, introduced: 11.0, deprecated: 13.0, renamed: "ipadGen1BadgePlay")
    @available(tvOS, introduced: 14.2, deprecated: 16.1, renamed: "ipadGen1BadgePlay")
    @available(watchOS, introduced: 7.1, deprecated: 9.1, renamed: "ipadGen1BadgePlay")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "ipadGen1BadgePlay")
    static var ipadHomebuttonBadgePlay: SFSymbol { .init(rawValue: "ipad.homebutton.badge.play") }

    /// 􀵑
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    @available(iOS, introduced: 14.2, deprecated: 16.1, renamed: "ipadGen1LandscapeBadgePlay")
    @available(macOS, introduced: 11.0, deprecated: 13.0, renamed: "ipadGen1LandscapeBadgePlay")
    @available(tvOS, introduced: 14.2, deprecated: 16.1, renamed: "ipadGen1LandscapeBadgePlay")
    @available(watchOS, introduced: 7.1, deprecated: 9.1, renamed: "ipadGen1LandscapeBadgePlay")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "ipadGen1LandscapeBadgePlay")
    static var ipadHomebuttonLandscapeBadgePlay: SFSymbol { .init(rawValue: "ipad.homebutton.landscape.badge.play") }

    /// 􀵒
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPad.
    static var ipadLandscapeBadgePlay: SFSymbol { .init(rawValue: "ipad.landscape.badge.play") }

    /// 􀴑
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static var iphoneBadgePlay: SFSymbol { .init(rawValue: "iphone.badge.play") }

    /// 􀐶
    /// Single Localization, 3 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    @available(iOS, introduced: 14.2, deprecated: 16.1, renamed: "iphoneGen1BadgePlay")
    @available(macOS, introduced: 11.0, deprecated: 13.0, renamed: "iphoneGen1BadgePlay")
    @available(tvOS, introduced: 14.2, deprecated: 16.1, renamed: "iphoneGen1BadgePlay")
    @available(watchOS, introduced: 7.1, deprecated: 9.1, renamed: "iphoneGen1BadgePlay")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "iphoneGen1BadgePlay")
    static var iphoneHomebuttonBadgePlay: SFSymbol { .init(rawValue: "iphone.homebutton.badge.play") }

    /// 􀴎
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    @available(iOS, introduced: 14.2, deprecated: 16.1, renamed: "iphoneGen1Landscape")
    @available(macOS, introduced: 11.0, deprecated: 13.0, renamed: "iphoneGen1Landscape")
    @available(tvOS, introduced: 14.2, deprecated: 16.1, renamed: "iphoneGen1Landscape")
    @available(watchOS, introduced: 7.1, deprecated: 9.1, renamed: "iphoneGen1Landscape")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "iphoneGen1Landscape")
    static var iphoneHomebuttonLandscape: SFSymbol { .init(rawValue: "iphone.homebutton.landscape") }

    /// 􀴏
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPhone.
    static var iphoneLandscape: SFSymbol { .init(rawValue: "iphone.landscape") }

    /// 􀴐
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s iPod touch.
    @available(iOS, introduced: 14.2, deprecated: 18.0, renamed: "ipodTouchLandscape")
    @available(macOS, introduced: 11.0, deprecated: 15.0, renamed: "ipodTouchLandscape")
    @available(tvOS, introduced: 14.2, deprecated: 18.0, renamed: "ipodTouchLandscape")
    @available(watchOS, introduced: 7.1, deprecated: 11.0, renamed: "ipodTouchLandscape")
    @available(visionOS, introduced: 1.0, deprecated: 2.0, renamed: "ipodTouchLandscape")
    static var ipodtouchLandscape: SFSymbol { .init(rawValue: "ipodtouch.landscape") }

    /// 􀵅
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Watch.
    static var lockApplewatch: SFSymbol { .init(rawValue: "lock.applewatch") }

    /// 􀵪
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var photoTv: SFSymbol { .init(rawValue: "photo.tv") }

    /// 􀵨
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var playTv: SFSymbol { .init(rawValue: "play.tv") }

    /// 􀵩
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var playTvFill: SFSymbol { .init(rawValue: "play.tv.fill") }

    /// 􀵚
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var rectangleBadgePersonCrop: SFSymbol { .init(rawValue: "rectangle.badge.person.crop") }

    /// 􀵛
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static var rectangleFillBadgePersonCrop: SFSymbol { .init(rawValue: "rectangle.fill.badge.person.crop") }

    /// 􀴊
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 14.2, deprecated: 14.5, renamed: "rectangleTopthirdInsetFill")
    @available(macOS, introduced: 11.0, deprecated: 11.3, renamed: "rectangleTopthirdInsetFill")
    @available(tvOS, introduced: 14.2, deprecated: 14.5, renamed: "rectangleTopthirdInsetFill")
    @available(watchOS, introduced: 7.1, deprecated: 7.4, renamed: "rectangleTopthirdInsetFill")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "rectangleTopthirdInsetFill")
    static var rectangleTopthirdInset: SFSymbol { .init(rawValue: "rectangle.topthird.inset") }

    /// 􀵍
    /// 3 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Hindi (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var repeat1Circle: SymbolWith2Localizations<Ar_v3, Hi_v3> { .init(rawValue: "repeat.1.circle") }

    /// 􀵎
    /// 3 Localizations, 3 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Hindi (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var repeat1CircleFill: SymbolWith2Localizations<Ar_v3, Hi_v3> { .init(rawValue: "repeat.1.circle.fill") }

    /// 􀵋
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var repeatCircle: SFSymbol { .init(rawValue: "repeat.circle") }

    /// 􀵌
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var repeatCircleFill: SFSymbol { .init(rawValue: "repeat.circle.fill") }

    /// 􀵔
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    @available(iOS, introduced: 14.2, deprecated: 15.0, renamed: "checkerboardShield")
    @available(macOS, introduced: 11.0, deprecated: 12.0, renamed: "checkerboardShield")
    @available(tvOS, introduced: 14.2, deprecated: 15.0, renamed: "checkerboardShield")
    @available(watchOS, introduced: 7.1, deprecated: 8.0, renamed: "checkerboardShield")
    @available(visionOS, introduced: 1.0, deprecated: 1.0, renamed: "checkerboardShield")
    static var shieldCheckerboard: SFSymbol { .init(rawValue: "shield.checkerboard") }

    /// 􀵉
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var shuffleCircle: SFSymbol { .init(rawValue: "shuffle.circle") }

    /// 􀵊
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var shuffleCircleFill: SFSymbol { .init(rawValue: "shuffle.circle.fill") }

    /// 􀵿
    /// 19 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Bengali (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Gujarati (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Kannada (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Malayalam (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Manipuri (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Maranthi (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Oriya (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Punjabi (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Santali (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Tamil (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Telugu (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    ///
    /// Layersets:
    /// - Monochrome
    static var textformatSizeLarger: SymbolWith18Localizations<Ar, Bn_v6, Gu_v6, He, Hi, Ja, Kn_v6, Ko, Ml_v6, Mni_v6, Mr_v6, Or_v6, Pa_v6, Sat_v6, Ta_v6, Te_v6, Th, Zh> { .init(rawValue: "textformat.size.larger") }

    /// 􀵷
    /// 19 Localizations, Single Layerset
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Bengali (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Gujarati (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Kannada (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Malayalam (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Manipuri (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Maranthi (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Oriya (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Punjabi (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Santali (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Tamil (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    /// - Telugu (iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0)
    ///
    /// Layersets:
    /// - Monochrome
    static var textformatSizeSmaller: SymbolWith18Localizations<Ar, Bn_v6, Gu_v6, He, Hi, Ja, Kn_v6, Ko, Ml_v6, Mni_v6, Mr_v6, Or_v6, Pa_v6, Sat_v6, Ta_v6, Te_v6, Th, Zh> { .init(rawValue: "textformat.size.smaller") }

    /// 􀴌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static var torus: SFSymbol { .init(rawValue: "torus") }

    /// 􀲰
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static var tvAndMediabox: SFSymbol { .init(rawValue: "tv.and.mediabox") }
}
