// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

public enum Localization: String, Equatable {
    case ar = "ar"
    case he = "he"
    case hi = "hi"
    case ja = "ja"
    case km = "km"
    case ko = "ko"
    case my = "my"
    case rtl = "rtl"
    case th = "th"
    case zh = "zh"
}

// MARK: - Static Localization

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ar: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var ar: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ar.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ar_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var ar: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ar.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ar_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var ar: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ar.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ar_v3: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, visionOS 1.0, *)
    public var ar: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ar.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ar_v4_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1, visionOS 1.0, *)
    public var ar: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ar.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ar_v4_2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4, visionOS 1.0, *)
    public var ar: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ar.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ar_v5_2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2, visionOS 1.1, *)
    public var ar: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ar.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct He: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var he: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.he.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct He_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var he: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.he.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct He_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var he: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.he.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Hi: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var hi: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.hi.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Hi_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var hi: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.hi.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Hi_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var hi: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.hi.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Hi_v3: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, visionOS 1.0, *)
    public var hi: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.hi.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Hi_v4_2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4, visionOS 1.0, *)
    public var hi: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.hi.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Hi_v5_2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2, visionOS 1.1, *)
    public var hi: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.hi.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ja: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var ja: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ja.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ja_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var ja: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ja.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ja_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var ja: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ja.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ja_v3: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, visionOS 1.0, *)
    public var ja: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ja.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Km: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var km: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.km.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Km_v5: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0, visionOS 1.0, *)
    public var km: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.km.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ko: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var ko: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ko.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ko_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var ko: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ko.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ko_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var ko: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ko.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Ko_v3: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, visionOS 1.0, *)
    public var ko: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.ko.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct My: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var my: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.my.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct My_v5: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0, visionOS 1.0, *)
    public var my: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.my.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Rtl: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var rtl: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.rtl.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Rtl_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var rtl: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.rtl.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Rtl_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var rtl: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.rtl.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Rtl_v4: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0, visionOS 1.0, *)
    public var rtl: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.rtl.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Rtl_v5: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0, visionOS 1.0, *)
    public var rtl: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.rtl.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Th: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var th: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.th.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Th_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var th: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.th.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Th_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var th: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.th.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Th_v3: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, visionOS 1.0, *)
    public var th: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.th.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Zh: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
    public var zh: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.zh.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Zh_v2: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, visionOS 1.0, *)
    public var zh: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.zh.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Zh_v2_1: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, visionOS 1.0, *)
    public var zh: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.zh.rawValue)") }
}

@available(iOS 13.0, macOS 11.0, tvOS 13.0, watchOS 6.0, visionOS 1.0, *)
public struct Zh_v3: SymbolLocalization {
    let source: SFSymbol
    public init(source: SFSymbol) { self.source = source }
    @available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, visionOS 1.0, *)
    public var zh: SFSymbol { .init(rawValue: "\(source.rawValue).\(Localization.zh.rawValue)") }
}
