// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool
@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension SymbolSet {
    /// Localize each symbol in the collection in Arabic.
    /// Symbols which are not localizable in Arabic remain unchanged.
    var ar: [SFSymbol] {
        map { symbol in
            if symbol is ar {
                return (symbol as! ar).ar
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is ar_v20 {
                return (symbol as! ar_v20).ar
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is ar_v21 {
                return (symbol as! ar_v21).ar
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is ar_v22 {
                return (symbol as! ar_v22).ar
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is ar_v30 {
                return (symbol as! ar_v30).ar
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is ar_v31 {
                return (symbol as! ar_v31).ar
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Hebrew.
    /// Symbols which are not localizable in Hebrew remain unchanged.
    var he: [SFSymbol] {
        map { symbol in
            if symbol is he {
                return (symbol as! he).he
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is he_v20 {
                return (symbol as! he_v20).he
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is he_v21 {
                return (symbol as! he_v21).he
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is he_v22 {
                return (symbol as! he_v22).he
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is he_v30 {
                return (symbol as! he_v30).he
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is he_v31 {
                return (symbol as! he_v31).he
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Hindi.
    /// Symbols which are not localizable in Hindi remain unchanged.
    var hi: [SFSymbol] {
        map { symbol in
            if symbol is hi {
                return (symbol as! hi).hi
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is hi_v20 {
                return (symbol as! hi_v20).hi
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is hi_v21 {
                return (symbol as! hi_v21).hi
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is hi_v22 {
                return (symbol as! hi_v22).hi
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is hi_v30 {
                return (symbol as! hi_v30).hi
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is hi_v31 {
                return (symbol as! hi_v31).hi
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Right-To-Left.
    /// Symbols which are not localizable in Right-To-Left remain unchanged.
    var rtl: [SFSymbol] {
        map { symbol in
            if symbol is rtl {
                return (symbol as! rtl).rtl
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is rtl_v20 {
                return (symbol as! rtl_v20).rtl
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is rtl_v21 {
                return (symbol as! rtl_v21).rtl
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is rtl_v22 {
                return (symbol as! rtl_v22).rtl
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is rtl_v30 {
                return (symbol as! rtl_v30).rtl
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is rtl_v31 {
                return (symbol as! rtl_v31).rtl
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Japanese.
    /// Symbols which are not localizable in Japanese remain unchanged.
    var ja: [SFSymbol] {
        map { symbol in
            if symbol is ja {
                return (symbol as! ja).ja
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is ja_v20 {
                return (symbol as! ja_v20).ja
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is ja_v21 {
                return (symbol as! ja_v21).ja
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is ja_v22 {
                return (symbol as! ja_v22).ja
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is ja_v30 {
                return (symbol as! ja_v30).ja
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is ja_v31 {
                return (symbol as! ja_v31).ja
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Korean.
    /// Symbols which are not localizable in Korean remain unchanged.
    var ko: [SFSymbol] {
        map { symbol in
            if symbol is ko {
                return (symbol as! ko).ko
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is ko_v20 {
                return (symbol as! ko_v20).ko
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is ko_v21 {
                return (symbol as! ko_v21).ko
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is ko_v22 {
                return (symbol as! ko_v22).ko
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is ko_v30 {
                return (symbol as! ko_v30).ko
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is ko_v31 {
                return (symbol as! ko_v31).ko
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Thai.
    /// Symbols which are not localizable in Thai remain unchanged.
    var th: [SFSymbol] {
        map { symbol in
            if symbol is th {
                return (symbol as! th).th
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is th_v20 {
                return (symbol as! th_v20).th
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is th_v21 {
                return (symbol as! th_v21).th
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is th_v22 {
                return (symbol as! th_v22).th
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is th_v30 {
                return (symbol as! th_v30).th
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is th_v31 {
                return (symbol as! th_v31).th
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Chinese.
    /// Symbols which are not localizable in Chinese remain unchanged.
    var zh: [SFSymbol] {
        map { symbol in
            if symbol is zh {
                return (symbol as! zh).zh
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is zh_v20 {
                return (symbol as! zh_v20).zh
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is zh_v21 {
                return (symbol as! zh_v21).zh
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is zh_v22 {
                return (symbol as! zh_v22).zh
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is zh_v30 {
                return (symbol as! zh_v30).zh
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is zh_v31 {
                return (symbol as! zh_v31).zh
            } else {
                return symbol
            }
        }
    }

    /// Localize each symbol in the collection in Traditional Chinese.
    /// Symbols which are not localizable in Traditional Chinese remain unchanged.
    var zhTraditional: [SFSymbol] {
        map { symbol in
            if symbol is zhTraditional {
                return (symbol as! zhTraditional).zhTraditional
            } else if #available(iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0, *), symbol is zhTraditional_v20 {
                return (symbol as! zhTraditional_v20).zhTraditional
            } else if #available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *), symbol is zhTraditional_v21 {
                return (symbol as! zhTraditional_v21).zhTraditional
            } else if #available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *), symbol is zhTraditional_v22 {
                return (symbol as! zhTraditional_v22).zhTraditional
            } else if #available(iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0, *), symbol is zhTraditional_v30 {
                return (symbol as! zhTraditional_v30).zhTraditional
            } else if #available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *), symbol is zhTraditional_v31 {
                return (symbol as! zhTraditional_v31).zhTraditional
            } else {
                return symbol
            }
        }
    }
}