
import Foundation

// Manually taken from https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/
// Last updated 16/12/2019
let asIsSymbols: [String: String] = [
    "airplayaudio": "AirPlay",
    "airplayvideo": "AirPlay",
    "arkit": "ARKit",
    "arrow.clockwise.icloud": "iCloud service",
    "arrow.counterclockwise.icloud": "iCloud service",
    "arrow.counterclockwise.icloud.fill": "iCloud service",
    "arrow.down.left.video": "FaceTime app",
    "arrow.down.left.video.fill": "FaceTime app",
    "arrow.up.right.video": "FaceTime app",
    "arrow.up.right.video.fill": "FaceTime app",
    "bolt.horizontal.icloud": "iCloud service",
    "bolt.horizontal.icloud.fill": "iCloud service",
    "exclamationmark.icloud": "iCloud service",
    "exclamationmark.icloud.fill": "iCloud service",
    "faceid": "Face ID",
    "icloud": "iCloud service",
    "icloud.and.arrow.down": "iCloud service",
    "icloud.and.arrow.down.fill": "iCloud service",
    "icloud.and.arrow.up": "iCloud service",
    "icloud.and.arrow.up.fill": "iCloud service",
    "icloud.circle": "iCloud service",
    "icloud.circle.fill": "iCloud service",
    "icloud.fill": "iCloud service",
    "icloud.slash": "iCloud service",
    "icloud.slash.fill": "iCloud service",
    "link.icloud": "iCloud service",
    "link.icloud.fill": "iCloud service",
    "livephoto": "Live Photos",
    "livephoto.play": "Live Photos",
    "livephoto.slash": "Live Photos",
    "lock.icloud": "iCloud service",
    "lock.icloud.fill": "iCloud service",
    "message": "Messages app",
    "message.circle": "Messages app",
    "message.circle.fill": "Messages app",
    "message.fill": "Messages app",
    "pencil.tip": "Markup feature",
    "pencil.tip.crop.circle": "Markup feature",
    "pencil.tip.crop.circle.badge.minus": "Markup feature",
    "pencil.tip.crop.circle.badge.plus": "Markup feature",
    "person.icloud": "iCloud service",
    "person.icloud.fill": "iCloud service",
    "questionmark.video": "FaceTime app",
    "questionmark.video.fill": "FaceTime app",
    "questionmark.video.fill.rtl": "FaceTime app",
    "questionmark.video.rtl": "FaceTime app",
    "realtimetext": "Real-time text feature",
    "safari": "Safari browser",
    "safari.fill": "Safari browser",
    "teletype": "Teletype feature",
    "video": "FaceTime app",
    "video.badge.plus": "FaceTime app",
    "video.badge.plus.fill": "FaceTime app",
    "video.circle": "FaceTime app",
    "video.circle.fill": "FaceTime app",
    "video.fill": "FaceTime app",
    "video.slash": "FaceTime app",
    "video.slash.fill": "FaceTime app",
    "xmark.icloud": "iCloud service",
    "xmark.icloud.fill": "iCloud service"
]
